// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"momoko/internal/data/ent/fileupload"
	"momoko/internal/data/ent/fileuploadchunk"
	"momoko/internal/data/ent/predicate"
	"momoko/internal/data/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FileUploadUpdate is the builder for updating FileUpload entities.
type FileUploadUpdate struct {
	config
	hooks    []Hook
	mutation *FileUploadMutation
}

// Where appends a list predicates to the FileUploadUpdate builder.
func (_u *FileUploadUpdate) Where(ps ...predicate.FileUpload) *FileUploadUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *FileUploadUpdate) SetUpdateTime(v time.Time) *FileUploadUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetHash sets the "hash" field.
func (_u *FileUploadUpdate) SetHash(v string) *FileUploadUpdate {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *FileUploadUpdate) SetNillableHash(v *string) *FileUploadUpdate {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *FileUploadUpdate) SetPath(v string) *FileUploadUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *FileUploadUpdate) SetNillablePath(v *string) *FileUploadUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *FileUploadUpdate) SetFileName(v string) *FileUploadUpdate {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *FileUploadUpdate) SetNillableFileName(v *string) *FileUploadUpdate {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *FileUploadUpdate) SetFileSize(v uint64) *FileUploadUpdate {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *FileUploadUpdate) SetNillableFileSize(v *uint64) *FileUploadUpdate {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *FileUploadUpdate) AddFileSize(v int64) *FileUploadUpdate {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetChunkSize sets the "chunk_size" field.
func (_u *FileUploadUpdate) SetChunkSize(v uint64) *FileUploadUpdate {
	_u.mutation.ResetChunkSize()
	_u.mutation.SetChunkSize(v)
	return _u
}

// SetNillableChunkSize sets the "chunk_size" field if the given value is not nil.
func (_u *FileUploadUpdate) SetNillableChunkSize(v *uint64) *FileUploadUpdate {
	if v != nil {
		_u.SetChunkSize(*v)
	}
	return _u
}

// AddChunkSize adds value to the "chunk_size" field.
func (_u *FileUploadUpdate) AddChunkSize(v int64) *FileUploadUpdate {
	_u.mutation.AddChunkSize(v)
	return _u
}

// SetTotalChunks sets the "total_chunks" field.
func (_u *FileUploadUpdate) SetTotalChunks(v uint64) *FileUploadUpdate {
	_u.mutation.ResetTotalChunks()
	_u.mutation.SetTotalChunks(v)
	return _u
}

// SetNillableTotalChunks sets the "total_chunks" field if the given value is not nil.
func (_u *FileUploadUpdate) SetNillableTotalChunks(v *uint64) *FileUploadUpdate {
	if v != nil {
		_u.SetTotalChunks(*v)
	}
	return _u
}

// AddTotalChunks adds value to the "total_chunks" field.
func (_u *FileUploadUpdate) AddTotalChunks(v int64) *FileUploadUpdate {
	_u.mutation.AddTotalChunks(v)
	return _u
}

// SetCompleted sets the "completed" field.
func (_u *FileUploadUpdate) SetCompleted(v bool) *FileUploadUpdate {
	_u.mutation.SetCompleted(v)
	return _u
}

// SetNillableCompleted sets the "completed" field if the given value is not nil.
func (_u *FileUploadUpdate) SetNillableCompleted(v *bool) *FileUploadUpdate {
	if v != nil {
		_u.SetCompleted(*v)
	}
	return _u
}

// SetCancel sets the "cancel" field.
func (_u *FileUploadUpdate) SetCancel(v bool) *FileUploadUpdate {
	_u.mutation.SetCancel(v)
	return _u
}

// SetNillableCancel sets the "cancel" field if the given value is not nil.
func (_u *FileUploadUpdate) SetNillableCancel(v *bool) *FileUploadUpdate {
	if v != nil {
		_u.SetCancel(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *FileUploadUpdate) SetUserID(v string) *FileUploadUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *FileUploadUpdate) SetNillableUserID(v *string) *FileUploadUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *FileUploadUpdate) SetUser(v *User) *FileUploadUpdate {
	return _u.SetUserID(v.ID)
}

// AddChunkIDs adds the "chunks" edge to the FileUploadChunk entity by IDs.
func (_u *FileUploadUpdate) AddChunkIDs(ids ...int) *FileUploadUpdate {
	_u.mutation.AddChunkIDs(ids...)
	return _u
}

// AddChunks adds the "chunks" edges to the FileUploadChunk entity.
func (_u *FileUploadUpdate) AddChunks(v ...*FileUploadChunk) *FileUploadUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChunkIDs(ids...)
}

// Mutation returns the FileUploadMutation object of the builder.
func (_u *FileUploadUpdate) Mutation() *FileUploadMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *FileUploadUpdate) ClearUser() *FileUploadUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearChunks clears all "chunks" edges to the FileUploadChunk entity.
func (_u *FileUploadUpdate) ClearChunks() *FileUploadUpdate {
	_u.mutation.ClearChunks()
	return _u
}

// RemoveChunkIDs removes the "chunks" edge to FileUploadChunk entities by IDs.
func (_u *FileUploadUpdate) RemoveChunkIDs(ids ...int) *FileUploadUpdate {
	_u.mutation.RemoveChunkIDs(ids...)
	return _u
}

// RemoveChunks removes "chunks" edges to FileUploadChunk entities.
func (_u *FileUploadUpdate) RemoveChunks(v ...*FileUploadChunk) *FileUploadUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChunkIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FileUploadUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FileUploadUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FileUploadUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FileUploadUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FileUploadUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := fileupload.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FileUploadUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FileUpload.user"`)
	}
	return nil
}

func (_u *FileUploadUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(fileupload.Table, fileupload.Columns, sqlgraph.NewFieldSpec(fileupload.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(fileupload.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(fileupload.FieldHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(fileupload.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(fileupload.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(fileupload.FieldFileSize, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(fileupload.FieldFileSize, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.ChunkSize(); ok {
		_spec.SetField(fileupload.FieldChunkSize, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedChunkSize(); ok {
		_spec.AddField(fileupload.FieldChunkSize, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.TotalChunks(); ok {
		_spec.SetField(fileupload.FieldTotalChunks, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedTotalChunks(); ok {
		_spec.AddField(fileupload.FieldTotalChunks, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Completed(); ok {
		_spec.SetField(fileupload.FieldCompleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Cancel(); ok {
		_spec.SetField(fileupload.FieldCancel, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   fileupload.UserTable,
			Columns: []string{fileupload.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   fileupload.UserTable,
			Columns: []string{fileupload.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChunksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   fileupload.ChunksTable,
			Columns: []string{fileupload.ChunksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fileuploadchunk.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChunksIDs(); len(nodes) > 0 && !_u.mutation.ChunksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   fileupload.ChunksTable,
			Columns: []string{fileupload.ChunksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fileuploadchunk.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChunksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   fileupload.ChunksTable,
			Columns: []string{fileupload.ChunksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fileuploadchunk.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fileupload.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FileUploadUpdateOne is the builder for updating a single FileUpload entity.
type FileUploadUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FileUploadMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *FileUploadUpdateOne) SetUpdateTime(v time.Time) *FileUploadUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetHash sets the "hash" field.
func (_u *FileUploadUpdateOne) SetHash(v string) *FileUploadUpdateOne {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *FileUploadUpdateOne) SetNillableHash(v *string) *FileUploadUpdateOne {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *FileUploadUpdateOne) SetPath(v string) *FileUploadUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *FileUploadUpdateOne) SetNillablePath(v *string) *FileUploadUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *FileUploadUpdateOne) SetFileName(v string) *FileUploadUpdateOne {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *FileUploadUpdateOne) SetNillableFileName(v *string) *FileUploadUpdateOne {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *FileUploadUpdateOne) SetFileSize(v uint64) *FileUploadUpdateOne {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *FileUploadUpdateOne) SetNillableFileSize(v *uint64) *FileUploadUpdateOne {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *FileUploadUpdateOne) AddFileSize(v int64) *FileUploadUpdateOne {
	_u.mutation.AddFileSize(v)
	return _u
}

// SetChunkSize sets the "chunk_size" field.
func (_u *FileUploadUpdateOne) SetChunkSize(v uint64) *FileUploadUpdateOne {
	_u.mutation.ResetChunkSize()
	_u.mutation.SetChunkSize(v)
	return _u
}

// SetNillableChunkSize sets the "chunk_size" field if the given value is not nil.
func (_u *FileUploadUpdateOne) SetNillableChunkSize(v *uint64) *FileUploadUpdateOne {
	if v != nil {
		_u.SetChunkSize(*v)
	}
	return _u
}

// AddChunkSize adds value to the "chunk_size" field.
func (_u *FileUploadUpdateOne) AddChunkSize(v int64) *FileUploadUpdateOne {
	_u.mutation.AddChunkSize(v)
	return _u
}

// SetTotalChunks sets the "total_chunks" field.
func (_u *FileUploadUpdateOne) SetTotalChunks(v uint64) *FileUploadUpdateOne {
	_u.mutation.ResetTotalChunks()
	_u.mutation.SetTotalChunks(v)
	return _u
}

// SetNillableTotalChunks sets the "total_chunks" field if the given value is not nil.
func (_u *FileUploadUpdateOne) SetNillableTotalChunks(v *uint64) *FileUploadUpdateOne {
	if v != nil {
		_u.SetTotalChunks(*v)
	}
	return _u
}

// AddTotalChunks adds value to the "total_chunks" field.
func (_u *FileUploadUpdateOne) AddTotalChunks(v int64) *FileUploadUpdateOne {
	_u.mutation.AddTotalChunks(v)
	return _u
}

// SetCompleted sets the "completed" field.
func (_u *FileUploadUpdateOne) SetCompleted(v bool) *FileUploadUpdateOne {
	_u.mutation.SetCompleted(v)
	return _u
}

// SetNillableCompleted sets the "completed" field if the given value is not nil.
func (_u *FileUploadUpdateOne) SetNillableCompleted(v *bool) *FileUploadUpdateOne {
	if v != nil {
		_u.SetCompleted(*v)
	}
	return _u
}

// SetCancel sets the "cancel" field.
func (_u *FileUploadUpdateOne) SetCancel(v bool) *FileUploadUpdateOne {
	_u.mutation.SetCancel(v)
	return _u
}

// SetNillableCancel sets the "cancel" field if the given value is not nil.
func (_u *FileUploadUpdateOne) SetNillableCancel(v *bool) *FileUploadUpdateOne {
	if v != nil {
		_u.SetCancel(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *FileUploadUpdateOne) SetUserID(v string) *FileUploadUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *FileUploadUpdateOne) SetNillableUserID(v *string) *FileUploadUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *FileUploadUpdateOne) SetUser(v *User) *FileUploadUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddChunkIDs adds the "chunks" edge to the FileUploadChunk entity by IDs.
func (_u *FileUploadUpdateOne) AddChunkIDs(ids ...int) *FileUploadUpdateOne {
	_u.mutation.AddChunkIDs(ids...)
	return _u
}

// AddChunks adds the "chunks" edges to the FileUploadChunk entity.
func (_u *FileUploadUpdateOne) AddChunks(v ...*FileUploadChunk) *FileUploadUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChunkIDs(ids...)
}

// Mutation returns the FileUploadMutation object of the builder.
func (_u *FileUploadUpdateOne) Mutation() *FileUploadMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *FileUploadUpdateOne) ClearUser() *FileUploadUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearChunks clears all "chunks" edges to the FileUploadChunk entity.
func (_u *FileUploadUpdateOne) ClearChunks() *FileUploadUpdateOne {
	_u.mutation.ClearChunks()
	return _u
}

// RemoveChunkIDs removes the "chunks" edge to FileUploadChunk entities by IDs.
func (_u *FileUploadUpdateOne) RemoveChunkIDs(ids ...int) *FileUploadUpdateOne {
	_u.mutation.RemoveChunkIDs(ids...)
	return _u
}

// RemoveChunks removes "chunks" edges to FileUploadChunk entities.
func (_u *FileUploadUpdateOne) RemoveChunks(v ...*FileUploadChunk) *FileUploadUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChunkIDs(ids...)
}

// Where appends a list predicates to the FileUploadUpdate builder.
func (_u *FileUploadUpdateOne) Where(ps ...predicate.FileUpload) *FileUploadUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FileUploadUpdateOne) Select(field string, fields ...string) *FileUploadUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FileUpload entity.
func (_u *FileUploadUpdateOne) Save(ctx context.Context) (*FileUpload, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FileUploadUpdateOne) SaveX(ctx context.Context) *FileUpload {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FileUploadUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FileUploadUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FileUploadUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := fileupload.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FileUploadUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FileUpload.user"`)
	}
	return nil
}

func (_u *FileUploadUpdateOne) sqlSave(ctx context.Context) (_node *FileUpload, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(fileupload.Table, fileupload.Columns, sqlgraph.NewFieldSpec(fileupload.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FileUpload.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fileupload.FieldID)
		for _, f := range fields {
			if !fileupload.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != fileupload.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(fileupload.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(fileupload.FieldHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(fileupload.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(fileupload.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(fileupload.FieldFileSize, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(fileupload.FieldFileSize, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.ChunkSize(); ok {
		_spec.SetField(fileupload.FieldChunkSize, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedChunkSize(); ok {
		_spec.AddField(fileupload.FieldChunkSize, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.TotalChunks(); ok {
		_spec.SetField(fileupload.FieldTotalChunks, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedTotalChunks(); ok {
		_spec.AddField(fileupload.FieldTotalChunks, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Completed(); ok {
		_spec.SetField(fileupload.FieldCompleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Cancel(); ok {
		_spec.SetField(fileupload.FieldCancel, field.TypeBool, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   fileupload.UserTable,
			Columns: []string{fileupload.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   fileupload.UserTable,
			Columns: []string{fileupload.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChunksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   fileupload.ChunksTable,
			Columns: []string{fileupload.ChunksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fileuploadchunk.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChunksIDs(); len(nodes) > 0 && !_u.mutation.ChunksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   fileupload.ChunksTable,
			Columns: []string{fileupload.ChunksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fileuploadchunk.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChunksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   fileupload.ChunksTable,
			Columns: []string{fileupload.ChunksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fileuploadchunk.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &FileUpload{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fileupload.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
