// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"momoko/internal/data/ent/fileupload"
	"momoko/internal/data/ent/fileuploadchunk"
	"momoko/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FileUploadChunkUpdate is the builder for updating FileUploadChunk entities.
type FileUploadChunkUpdate struct {
	config
	hooks    []Hook
	mutation *FileUploadChunkMutation
}

// Where appends a list predicates to the FileUploadChunkUpdate builder.
func (_u *FileUploadChunkUpdate) Where(ps ...predicate.FileUploadChunk) *FileUploadChunkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *FileUploadChunkUpdate) SetUpdateTime(v time.Time) *FileUploadChunkUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetUploadID sets the "upload_id" field.
func (_u *FileUploadChunkUpdate) SetUploadID(v string) *FileUploadChunkUpdate {
	_u.mutation.SetUploadID(v)
	return _u
}

// SetNillableUploadID sets the "upload_id" field if the given value is not nil.
func (_u *FileUploadChunkUpdate) SetNillableUploadID(v *string) *FileUploadChunkUpdate {
	if v != nil {
		_u.SetUploadID(*v)
	}
	return _u
}

// SetChunk sets the "chunk" field.
func (_u *FileUploadChunkUpdate) SetChunk(v uint64) *FileUploadChunkUpdate {
	_u.mutation.ResetChunk()
	_u.mutation.SetChunk(v)
	return _u
}

// SetNillableChunk sets the "chunk" field if the given value is not nil.
func (_u *FileUploadChunkUpdate) SetNillableChunk(v *uint64) *FileUploadChunkUpdate {
	if v != nil {
		_u.SetChunk(*v)
	}
	return _u
}

// AddChunk adds value to the "chunk" field.
func (_u *FileUploadChunkUpdate) AddChunk(v int64) *FileUploadChunkUpdate {
	_u.mutation.AddChunk(v)
	return _u
}

// SetHash sets the "hash" field.
func (_u *FileUploadChunkUpdate) SetHash(v string) *FileUploadChunkUpdate {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *FileUploadChunkUpdate) SetNillableHash(v *string) *FileUploadChunkUpdate {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// SetSize sets the "size" field.
func (_u *FileUploadChunkUpdate) SetSize(v uint64) *FileUploadChunkUpdate {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *FileUploadChunkUpdate) SetNillableSize(v *uint64) *FileUploadChunkUpdate {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *FileUploadChunkUpdate) AddSize(v int64) *FileUploadChunkUpdate {
	_u.mutation.AddSize(v)
	return _u
}

// SetUpload sets the "upload" edge to the FileUpload entity.
func (_u *FileUploadChunkUpdate) SetUpload(v *FileUpload) *FileUploadChunkUpdate {
	return _u.SetUploadID(v.ID)
}

// Mutation returns the FileUploadChunkMutation object of the builder.
func (_u *FileUploadChunkUpdate) Mutation() *FileUploadChunkMutation {
	return _u.mutation
}

// ClearUpload clears the "upload" edge to the FileUpload entity.
func (_u *FileUploadChunkUpdate) ClearUpload() *FileUploadChunkUpdate {
	_u.mutation.ClearUpload()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FileUploadChunkUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FileUploadChunkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FileUploadChunkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FileUploadChunkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FileUploadChunkUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := fileuploadchunk.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FileUploadChunkUpdate) check() error {
	if _u.mutation.UploadCleared() && len(_u.mutation.UploadIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FileUploadChunk.upload"`)
	}
	return nil
}

func (_u *FileUploadChunkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(fileuploadchunk.Table, fileuploadchunk.Columns, sqlgraph.NewFieldSpec(fileuploadchunk.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(fileuploadchunk.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Chunk(); ok {
		_spec.SetField(fileuploadchunk.FieldChunk, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedChunk(); ok {
		_spec.AddField(fileuploadchunk.FieldChunk, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(fileuploadchunk.FieldHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(fileuploadchunk.FieldSize, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(fileuploadchunk.FieldSize, field.TypeUint64, value)
	}
	if _u.mutation.UploadCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   fileuploadchunk.UploadTable,
			Columns: []string{fileuploadchunk.UploadColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fileupload.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UploadIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   fileuploadchunk.UploadTable,
			Columns: []string{fileuploadchunk.UploadColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fileupload.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fileuploadchunk.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FileUploadChunkUpdateOne is the builder for updating a single FileUploadChunk entity.
type FileUploadChunkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FileUploadChunkMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *FileUploadChunkUpdateOne) SetUpdateTime(v time.Time) *FileUploadChunkUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetUploadID sets the "upload_id" field.
func (_u *FileUploadChunkUpdateOne) SetUploadID(v string) *FileUploadChunkUpdateOne {
	_u.mutation.SetUploadID(v)
	return _u
}

// SetNillableUploadID sets the "upload_id" field if the given value is not nil.
func (_u *FileUploadChunkUpdateOne) SetNillableUploadID(v *string) *FileUploadChunkUpdateOne {
	if v != nil {
		_u.SetUploadID(*v)
	}
	return _u
}

// SetChunk sets the "chunk" field.
func (_u *FileUploadChunkUpdateOne) SetChunk(v uint64) *FileUploadChunkUpdateOne {
	_u.mutation.ResetChunk()
	_u.mutation.SetChunk(v)
	return _u
}

// SetNillableChunk sets the "chunk" field if the given value is not nil.
func (_u *FileUploadChunkUpdateOne) SetNillableChunk(v *uint64) *FileUploadChunkUpdateOne {
	if v != nil {
		_u.SetChunk(*v)
	}
	return _u
}

// AddChunk adds value to the "chunk" field.
func (_u *FileUploadChunkUpdateOne) AddChunk(v int64) *FileUploadChunkUpdateOne {
	_u.mutation.AddChunk(v)
	return _u
}

// SetHash sets the "hash" field.
func (_u *FileUploadChunkUpdateOne) SetHash(v string) *FileUploadChunkUpdateOne {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *FileUploadChunkUpdateOne) SetNillableHash(v *string) *FileUploadChunkUpdateOne {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// SetSize sets the "size" field.
func (_u *FileUploadChunkUpdateOne) SetSize(v uint64) *FileUploadChunkUpdateOne {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *FileUploadChunkUpdateOne) SetNillableSize(v *uint64) *FileUploadChunkUpdateOne {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *FileUploadChunkUpdateOne) AddSize(v int64) *FileUploadChunkUpdateOne {
	_u.mutation.AddSize(v)
	return _u
}

// SetUpload sets the "upload" edge to the FileUpload entity.
func (_u *FileUploadChunkUpdateOne) SetUpload(v *FileUpload) *FileUploadChunkUpdateOne {
	return _u.SetUploadID(v.ID)
}

// Mutation returns the FileUploadChunkMutation object of the builder.
func (_u *FileUploadChunkUpdateOne) Mutation() *FileUploadChunkMutation {
	return _u.mutation
}

// ClearUpload clears the "upload" edge to the FileUpload entity.
func (_u *FileUploadChunkUpdateOne) ClearUpload() *FileUploadChunkUpdateOne {
	_u.mutation.ClearUpload()
	return _u
}

// Where appends a list predicates to the FileUploadChunkUpdate builder.
func (_u *FileUploadChunkUpdateOne) Where(ps ...predicate.FileUploadChunk) *FileUploadChunkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FileUploadChunkUpdateOne) Select(field string, fields ...string) *FileUploadChunkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FileUploadChunk entity.
func (_u *FileUploadChunkUpdateOne) Save(ctx context.Context) (*FileUploadChunk, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FileUploadChunkUpdateOne) SaveX(ctx context.Context) *FileUploadChunk {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FileUploadChunkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FileUploadChunkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FileUploadChunkUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := fileuploadchunk.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FileUploadChunkUpdateOne) check() error {
	if _u.mutation.UploadCleared() && len(_u.mutation.UploadIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FileUploadChunk.upload"`)
	}
	return nil
}

func (_u *FileUploadChunkUpdateOne) sqlSave(ctx context.Context) (_node *FileUploadChunk, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(fileuploadchunk.Table, fileuploadchunk.Columns, sqlgraph.NewFieldSpec(fileuploadchunk.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FileUploadChunk.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fileuploadchunk.FieldID)
		for _, f := range fields {
			if !fileuploadchunk.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != fileuploadchunk.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(fileuploadchunk.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Chunk(); ok {
		_spec.SetField(fileuploadchunk.FieldChunk, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedChunk(); ok {
		_spec.AddField(fileuploadchunk.FieldChunk, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(fileuploadchunk.FieldHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(fileuploadchunk.FieldSize, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(fileuploadchunk.FieldSize, field.TypeUint64, value)
	}
	if _u.mutation.UploadCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   fileuploadchunk.UploadTable,
			Columns: []string{fileuploadchunk.UploadColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fileupload.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UploadIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   fileuploadchunk.UploadTable,
			Columns: []string{fileuploadchunk.UploadColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(fileupload.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &FileUploadChunk{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{fileuploadchunk.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
