// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"momoko/internal/data/ent/instance"
	"momoko/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InstanceUpdate is the builder for updating Instance entities.
type InstanceUpdate struct {
	config
	hooks    []Hook
	mutation *InstanceMutation
}

// Where appends a list predicates to the InstanceUpdate builder.
func (_u *InstanceUpdate) Where(ps ...predicate.Instance) *InstanceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *InstanceUpdate) SetName(v string) *InstanceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *InstanceUpdate) SetNillableName(v *string) *InstanceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetIsSystem sets the "is_system" field.
func (_u *InstanceUpdate) SetIsSystem(v bool) *InstanceUpdate {
	_u.mutation.SetIsSystem(v)
	return _u
}

// SetNillableIsSystem sets the "is_system" field if the given value is not nil.
func (_u *InstanceUpdate) SetNillableIsSystem(v *bool) *InstanceUpdate {
	if v != nil {
		_u.SetIsSystem(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *InstanceUpdate) SetUserID(v string) *InstanceUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InstanceUpdate) SetNillableUserID(v *string) *InstanceUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *InstanceUpdate) SetPath(v string) *InstanceUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *InstanceUpdate) SetNillablePath(v *string) *InstanceUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetStartCommand sets the "start_command" field.
func (_u *InstanceUpdate) SetStartCommand(v string) *InstanceUpdate {
	_u.mutation.SetStartCommand(v)
	return _u
}

// SetNillableStartCommand sets the "start_command" field if the given value is not nil.
func (_u *InstanceUpdate) SetNillableStartCommand(v *string) *InstanceUpdate {
	if v != nil {
		_u.SetStartCommand(*v)
	}
	return _u
}

// Mutation returns the InstanceMutation object of the builder.
func (_u *InstanceUpdate) Mutation() *InstanceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InstanceUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InstanceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InstanceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InstanceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InstanceUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := instance.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Instance.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := instance.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Instance.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := instance.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Instance.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StartCommand(); ok {
		if err := instance.StartCommandValidator(v); err != nil {
			return &ValidationError{Name: "start_command", err: fmt.Errorf(`ent: validator failed for field "Instance.start_command": %w`, err)}
		}
	}
	return nil
}

func (_u *InstanceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(instance.Table, instance.Columns, sqlgraph.NewFieldSpec(instance.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(instance.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsSystem(); ok {
		_spec.SetField(instance.FieldIsSystem, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(instance.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(instance.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartCommand(); ok {
		_spec.SetField(instance.FieldStartCommand, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{instance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InstanceUpdateOne is the builder for updating a single Instance entity.
type InstanceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InstanceMutation
}

// SetName sets the "name" field.
func (_u *InstanceUpdateOne) SetName(v string) *InstanceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *InstanceUpdateOne) SetNillableName(v *string) *InstanceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetIsSystem sets the "is_system" field.
func (_u *InstanceUpdateOne) SetIsSystem(v bool) *InstanceUpdateOne {
	_u.mutation.SetIsSystem(v)
	return _u
}

// SetNillableIsSystem sets the "is_system" field if the given value is not nil.
func (_u *InstanceUpdateOne) SetNillableIsSystem(v *bool) *InstanceUpdateOne {
	if v != nil {
		_u.SetIsSystem(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *InstanceUpdateOne) SetUserID(v string) *InstanceUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *InstanceUpdateOne) SetNillableUserID(v *string) *InstanceUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *InstanceUpdateOne) SetPath(v string) *InstanceUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *InstanceUpdateOne) SetNillablePath(v *string) *InstanceUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetStartCommand sets the "start_command" field.
func (_u *InstanceUpdateOne) SetStartCommand(v string) *InstanceUpdateOne {
	_u.mutation.SetStartCommand(v)
	return _u
}

// SetNillableStartCommand sets the "start_command" field if the given value is not nil.
func (_u *InstanceUpdateOne) SetNillableStartCommand(v *string) *InstanceUpdateOne {
	if v != nil {
		_u.SetStartCommand(*v)
	}
	return _u
}

// Mutation returns the InstanceMutation object of the builder.
func (_u *InstanceUpdateOne) Mutation() *InstanceMutation {
	return _u.mutation
}

// Where appends a list predicates to the InstanceUpdate builder.
func (_u *InstanceUpdateOne) Where(ps ...predicate.Instance) *InstanceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InstanceUpdateOne) Select(field string, fields ...string) *InstanceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Instance entity.
func (_u *InstanceUpdateOne) Save(ctx context.Context) (*Instance, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InstanceUpdateOne) SaveX(ctx context.Context) *Instance {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InstanceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InstanceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InstanceUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := instance.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Instance.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UserID(); ok {
		if err := instance.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Instance.user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := instance.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Instance.path": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StartCommand(); ok {
		if err := instance.StartCommandValidator(v); err != nil {
			return &ValidationError{Name: "start_command", err: fmt.Errorf(`ent: validator failed for field "Instance.start_command": %w`, err)}
		}
	}
	return nil
}

func (_u *InstanceUpdateOne) sqlSave(ctx context.Context) (_node *Instance, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(instance.Table, instance.Columns, sqlgraph.NewFieldSpec(instance.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Instance.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, instance.FieldID)
		for _, f := range fields {
			if !instance.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != instance.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(instance.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsSystem(); ok {
		_spec.SetField(instance.FieldIsSystem, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(instance.FieldUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(instance.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartCommand(); ok {
		_spec.SetField(instance.FieldStartCommand, field.TypeString, value)
	}
	_node = &Instance{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{instance.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
