// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"momoko/internal/data/ent/instancetype"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// InstanceType is the model entity for the InstanceType schema.
type InstanceType struct {
	config `json:"-"`
	// ID of the ent.
	// 类型id
	ID string `json:"id,omitempty"`
	// 类型名称
	Name string `json:"name,omitempty"`
	// 是否系统内置
	IsSystem     bool `json:"is_system,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*InstanceType) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case instancetype.FieldIsSystem:
			values[i] = new(sql.NullBool)
		case instancetype.FieldID, instancetype.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the InstanceType fields.
func (_m *InstanceType) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case instancetype.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case instancetype.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case instancetype.FieldIsSystem:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_system", values[i])
			} else if value.Valid {
				_m.IsSystem = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the InstanceType.
// This includes values selected through modifiers, order, etc.
func (_m *InstanceType) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this InstanceType.
// Note that you need to call InstanceType.Unwrap() before calling this method if this InstanceType
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *InstanceType) Update() *InstanceTypeUpdateOne {
	return NewInstanceTypeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the InstanceType entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *InstanceType) Unwrap() *InstanceType {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: InstanceType is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *InstanceType) String() string {
	var builder strings.Builder
	builder.WriteString("InstanceType(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("is_system=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsSystem))
	builder.WriteByte(')')
	return builder.String()
}

// InstanceTypes is a parsable slice of InstanceType.
type InstanceTypes []*InstanceType
