// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"momoko/internal/data/ent/instance"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InstanceCreate is the builder for creating a Instance entity.
type InstanceCreate struct {
	config
	mutation *InstanceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *InstanceCreate) SetName(v string) *InstanceCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetIsSystem sets the "is_system" field.
func (_c *InstanceCreate) SetIsSystem(v bool) *InstanceCreate {
	_c.mutation.SetIsSystem(v)
	return _c
}

// SetNillableIsSystem sets the "is_system" field if the given value is not nil.
func (_c *InstanceCreate) SetNillableIsSystem(v *bool) *InstanceCreate {
	if v != nil {
		_c.SetIsSystem(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *InstanceCreate) SetUserID(v string) *InstanceCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPath sets the "path" field.
func (_c *InstanceCreate) SetPath(v string) *InstanceCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_c *InstanceCreate) SetNillablePath(v *string) *InstanceCreate {
	if v != nil {
		_c.SetPath(*v)
	}
	return _c
}

// SetStartCommand sets the "start_command" field.
func (_c *InstanceCreate) SetStartCommand(v string) *InstanceCreate {
	_c.mutation.SetStartCommand(v)
	return _c
}

// SetID sets the "id" field.
func (_c *InstanceCreate) SetID(v string) *InstanceCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the InstanceMutation object of the builder.
func (_c *InstanceCreate) Mutation() *InstanceMutation {
	return _c.mutation
}

// Save creates the Instance in the database.
func (_c *InstanceCreate) Save(ctx context.Context) (*Instance, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InstanceCreate) SaveX(ctx context.Context) *Instance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InstanceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InstanceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InstanceCreate) defaults() {
	if _, ok := _c.mutation.IsSystem(); !ok {
		v := instance.DefaultIsSystem
		_c.mutation.SetIsSystem(v)
	}
	if _, ok := _c.mutation.Path(); !ok {
		v := instance.DefaultPath
		_c.mutation.SetPath(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InstanceCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Instance.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := instance.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Instance.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsSystem(); !ok {
		return &ValidationError{Name: "is_system", err: errors.New(`ent: missing required field "Instance.is_system"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Instance.user_id"`)}
	}
	if v, ok := _c.mutation.UserID(); ok {
		if err := instance.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Instance.user_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "Instance.path"`)}
	}
	if v, ok := _c.mutation.Path(); ok {
		if err := instance.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "Instance.path": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StartCommand(); !ok {
		return &ValidationError{Name: "start_command", err: errors.New(`ent: missing required field "Instance.start_command"`)}
	}
	if v, ok := _c.mutation.StartCommand(); ok {
		if err := instance.StartCommandValidator(v); err != nil {
			return &ValidationError{Name: "start_command", err: fmt.Errorf(`ent: validator failed for field "Instance.start_command": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := instance.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Instance.id": %w`, err)}
		}
	}
	return nil
}

func (_c *InstanceCreate) sqlSave(ctx context.Context) (*Instance, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Instance.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InstanceCreate) createSpec() (*Instance, *sqlgraph.CreateSpec) {
	var (
		_node = &Instance{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(instance.Table, sqlgraph.NewFieldSpec(instance.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(instance.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.IsSystem(); ok {
		_spec.SetField(instance.FieldIsSystem, field.TypeBool, value)
		_node.IsSystem = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(instance.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(instance.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.StartCommand(); ok {
		_spec.SetField(instance.FieldStartCommand, field.TypeString, value)
		_node.StartCommand = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Instance.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InstanceUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *InstanceCreate) OnConflict(opts ...sql.ConflictOption) *InstanceUpsertOne {
	_c.conflict = opts
	return &InstanceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Instance.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InstanceCreate) OnConflictColumns(columns ...string) *InstanceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InstanceUpsertOne{
		create: _c,
	}
}

type (
	// InstanceUpsertOne is the builder for "upsert"-ing
	//  one Instance node.
	InstanceUpsertOne struct {
		create *InstanceCreate
	}

	// InstanceUpsert is the "OnConflict" setter.
	InstanceUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *InstanceUpsert) SetName(v string) *InstanceUpsert {
	u.Set(instance.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *InstanceUpsert) UpdateName() *InstanceUpsert {
	u.SetExcluded(instance.FieldName)
	return u
}

// SetIsSystem sets the "is_system" field.
func (u *InstanceUpsert) SetIsSystem(v bool) *InstanceUpsert {
	u.Set(instance.FieldIsSystem, v)
	return u
}

// UpdateIsSystem sets the "is_system" field to the value that was provided on create.
func (u *InstanceUpsert) UpdateIsSystem() *InstanceUpsert {
	u.SetExcluded(instance.FieldIsSystem)
	return u
}

// SetUserID sets the "user_id" field.
func (u *InstanceUpsert) SetUserID(v string) *InstanceUpsert {
	u.Set(instance.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InstanceUpsert) UpdateUserID() *InstanceUpsert {
	u.SetExcluded(instance.FieldUserID)
	return u
}

// SetPath sets the "path" field.
func (u *InstanceUpsert) SetPath(v string) *InstanceUpsert {
	u.Set(instance.FieldPath, v)
	return u
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *InstanceUpsert) UpdatePath() *InstanceUpsert {
	u.SetExcluded(instance.FieldPath)
	return u
}

// SetStartCommand sets the "start_command" field.
func (u *InstanceUpsert) SetStartCommand(v string) *InstanceUpsert {
	u.Set(instance.FieldStartCommand, v)
	return u
}

// UpdateStartCommand sets the "start_command" field to the value that was provided on create.
func (u *InstanceUpsert) UpdateStartCommand() *InstanceUpsert {
	u.SetExcluded(instance.FieldStartCommand)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Instance.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(instance.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *InstanceUpsertOne) UpdateNewValues() *InstanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(instance.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Instance.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InstanceUpsertOne) Ignore() *InstanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InstanceUpsertOne) DoNothing() *InstanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InstanceCreate.OnConflict
// documentation for more info.
func (u *InstanceUpsertOne) Update(set func(*InstanceUpsert)) *InstanceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InstanceUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *InstanceUpsertOne) SetName(v string) *InstanceUpsertOne {
	return u.Update(func(s *InstanceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *InstanceUpsertOne) UpdateName() *InstanceUpsertOne {
	return u.Update(func(s *InstanceUpsert) {
		s.UpdateName()
	})
}

// SetIsSystem sets the "is_system" field.
func (u *InstanceUpsertOne) SetIsSystem(v bool) *InstanceUpsertOne {
	return u.Update(func(s *InstanceUpsert) {
		s.SetIsSystem(v)
	})
}

// UpdateIsSystem sets the "is_system" field to the value that was provided on create.
func (u *InstanceUpsertOne) UpdateIsSystem() *InstanceUpsertOne {
	return u.Update(func(s *InstanceUpsert) {
		s.UpdateIsSystem()
	})
}

// SetUserID sets the "user_id" field.
func (u *InstanceUpsertOne) SetUserID(v string) *InstanceUpsertOne {
	return u.Update(func(s *InstanceUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InstanceUpsertOne) UpdateUserID() *InstanceUpsertOne {
	return u.Update(func(s *InstanceUpsert) {
		s.UpdateUserID()
	})
}

// SetPath sets the "path" field.
func (u *InstanceUpsertOne) SetPath(v string) *InstanceUpsertOne {
	return u.Update(func(s *InstanceUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *InstanceUpsertOne) UpdatePath() *InstanceUpsertOne {
	return u.Update(func(s *InstanceUpsert) {
		s.UpdatePath()
	})
}

// SetStartCommand sets the "start_command" field.
func (u *InstanceUpsertOne) SetStartCommand(v string) *InstanceUpsertOne {
	return u.Update(func(s *InstanceUpsert) {
		s.SetStartCommand(v)
	})
}

// UpdateStartCommand sets the "start_command" field to the value that was provided on create.
func (u *InstanceUpsertOne) UpdateStartCommand() *InstanceUpsertOne {
	return u.Update(func(s *InstanceUpsert) {
		s.UpdateStartCommand()
	})
}

// Exec executes the query.
func (u *InstanceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InstanceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InstanceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InstanceUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: InstanceUpsertOne.ID is not supported by MySQL driver. Use InstanceUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InstanceUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InstanceCreateBulk is the builder for creating many Instance entities in bulk.
type InstanceCreateBulk struct {
	config
	err      error
	builders []*InstanceCreate
	conflict []sql.ConflictOption
}

// Save creates the Instance entities in the database.
func (_c *InstanceCreateBulk) Save(ctx context.Context) ([]*Instance, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Instance, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InstanceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InstanceCreateBulk) SaveX(ctx context.Context) []*Instance {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InstanceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InstanceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Instance.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InstanceUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *InstanceCreateBulk) OnConflict(opts ...sql.ConflictOption) *InstanceUpsertBulk {
	_c.conflict = opts
	return &InstanceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Instance.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InstanceCreateBulk) OnConflictColumns(columns ...string) *InstanceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InstanceUpsertBulk{
		create: _c,
	}
}

// InstanceUpsertBulk is the builder for "upsert"-ing
// a bulk of Instance nodes.
type InstanceUpsertBulk struct {
	create *InstanceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Instance.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(instance.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *InstanceUpsertBulk) UpdateNewValues() *InstanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(instance.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Instance.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InstanceUpsertBulk) Ignore() *InstanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InstanceUpsertBulk) DoNothing() *InstanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InstanceCreateBulk.OnConflict
// documentation for more info.
func (u *InstanceUpsertBulk) Update(set func(*InstanceUpsert)) *InstanceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InstanceUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *InstanceUpsertBulk) SetName(v string) *InstanceUpsertBulk {
	return u.Update(func(s *InstanceUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *InstanceUpsertBulk) UpdateName() *InstanceUpsertBulk {
	return u.Update(func(s *InstanceUpsert) {
		s.UpdateName()
	})
}

// SetIsSystem sets the "is_system" field.
func (u *InstanceUpsertBulk) SetIsSystem(v bool) *InstanceUpsertBulk {
	return u.Update(func(s *InstanceUpsert) {
		s.SetIsSystem(v)
	})
}

// UpdateIsSystem sets the "is_system" field to the value that was provided on create.
func (u *InstanceUpsertBulk) UpdateIsSystem() *InstanceUpsertBulk {
	return u.Update(func(s *InstanceUpsert) {
		s.UpdateIsSystem()
	})
}

// SetUserID sets the "user_id" field.
func (u *InstanceUpsertBulk) SetUserID(v string) *InstanceUpsertBulk {
	return u.Update(func(s *InstanceUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *InstanceUpsertBulk) UpdateUserID() *InstanceUpsertBulk {
	return u.Update(func(s *InstanceUpsert) {
		s.UpdateUserID()
	})
}

// SetPath sets the "path" field.
func (u *InstanceUpsertBulk) SetPath(v string) *InstanceUpsertBulk {
	return u.Update(func(s *InstanceUpsert) {
		s.SetPath(v)
	})
}

// UpdatePath sets the "path" field to the value that was provided on create.
func (u *InstanceUpsertBulk) UpdatePath() *InstanceUpsertBulk {
	return u.Update(func(s *InstanceUpsert) {
		s.UpdatePath()
	})
}

// SetStartCommand sets the "start_command" field.
func (u *InstanceUpsertBulk) SetStartCommand(v string) *InstanceUpsertBulk {
	return u.Update(func(s *InstanceUpsert) {
		s.SetStartCommand(v)
	})
}

// UpdateStartCommand sets the "start_command" field to the value that was provided on create.
func (u *InstanceUpsertBulk) UpdateStartCommand() *InstanceUpsertBulk {
	return u.Update(func(s *InstanceUpsert) {
		s.UpdateStartCommand()
	})
}

// Exec executes the query.
func (u *InstanceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InstanceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InstanceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InstanceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
