// Code generated by ent, DO NOT EDIT.

package ent

import (
	"momoko/internal/data/ent/admin"
	"momoko/internal/data/ent/auth"
	"momoko/internal/data/ent/menu"
	"momoko/internal/data/ent/role"
	"momoko/internal/data/ent/schema"
	"momoko/internal/data/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	adminFields := schema.Admin{}.Fields()
	_ = adminFields
	// adminDescName is the schema descriptor for name field.
	adminDescName := adminFields[1].Descriptor()
	// admin.DefaultName holds the default value on creation for the name field.
	admin.DefaultName = adminDescName.Default.(string)
	// adminDescEmail is the schema descriptor for email field.
	adminDescEmail := adminFields[2].Descriptor()
	// admin.DefaultEmail holds the default value on creation for the email field.
	admin.DefaultEmail = adminDescEmail.Default.(string)
	// adminDescAvatar is the schema descriptor for avatar field.
	adminDescAvatar := adminFields[3].Descriptor()
	// admin.DefaultAvatar holds the default value on creation for the avatar field.
	admin.DefaultAvatar = adminDescAvatar.Default.(string)
	// adminDescAccess is the schema descriptor for access field.
	adminDescAccess := adminFields[4].Descriptor()
	// admin.DefaultAccess holds the default value on creation for the access field.
	admin.DefaultAccess = adminDescAccess.Default.(string)
	// adminDescPassword is the schema descriptor for password field.
	adminDescPassword := adminFields[5].Descriptor()
	// admin.DefaultPassword holds the default value on creation for the password field.
	admin.DefaultPassword = adminDescPassword.Default.(string)
	// adminDescCreateTime is the schema descriptor for create_time field.
	adminDescCreateTime := adminFields[6].Descriptor()
	// admin.DefaultCreateTime holds the default value on creation for the create_time field.
	admin.DefaultCreateTime = adminDescCreateTime.Default.(func() time.Time)
	// adminDescUpdateTime is the schema descriptor for update_time field.
	adminDescUpdateTime := adminFields[7].Descriptor()
	// admin.DefaultUpdateTime holds the default value on creation for the update_time field.
	admin.DefaultUpdateTime = adminDescUpdateTime.Default.(func() time.Time)
	// admin.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	admin.UpdateDefaultUpdateTime = adminDescUpdateTime.UpdateDefault.(func() time.Time)
	authFields := schema.Auth{}.Fields()
	_ = authFields
	// authDescSessionID is the schema descriptor for session_id field.
	authDescSessionID := authFields[0].Descriptor()
	// auth.SessionIDValidator is a validator for the "session_id" field. It is called by the builders before save.
	auth.SessionIDValidator = authDescSessionID.Validators[0].(func(string) error)
	// authDescDeviceID is the schema descriptor for device_id field.
	authDescDeviceID := authFields[1].Descriptor()
	// auth.DeviceIDValidator is a validator for the "device_id" field. It is called by the builders before save.
	auth.DeviceIDValidator = authDescDeviceID.Validators[0].(func(string) error)
	// authDescUserID is the schema descriptor for user_id field.
	authDescUserID := authFields[2].Descriptor()
	// auth.UserIDValidator is a validator for the "user_id" field. It is called by the builders before save.
	auth.UserIDValidator = authDescUserID.Validators[0].(func(string) error)
	// authDescCreateTime is the schema descriptor for create_time field.
	authDescCreateTime := authFields[3].Descriptor()
	// auth.DefaultCreateTime holds the default value on creation for the create_time field.
	auth.DefaultCreateTime = authDescCreateTime.Default.(func() time.Time)
	// authDescUpdateTime is the schema descriptor for update_time field.
	authDescUpdateTime := authFields[4].Descriptor()
	// auth.DefaultUpdateTime holds the default value on creation for the update_time field.
	auth.DefaultUpdateTime = authDescUpdateTime.Default.(func() time.Time)
	// auth.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	auth.UpdateDefaultUpdateTime = authDescUpdateTime.UpdateDefault.(func() time.Time)
	menuFields := schema.Menu{}.Fields()
	_ = menuFields
	// menuDescTitle is the schema descriptor for title field.
	menuDescTitle := menuFields[2].Descriptor()
	// menu.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	menu.TitleValidator = menuDescTitle.Validators[0].(func(string) error)
	// menuDescIcon is the schema descriptor for icon field.
	menuDescIcon := menuFields[3].Descriptor()
	// menu.IconValidator is a validator for the "icon" field. It is called by the builders before save.
	menu.IconValidator = menuDescIcon.Validators[0].(func(string) error)
	// menuDescIsBuiltin is the schema descriptor for is_builtin field.
	menuDescIsBuiltin := menuFields[4].Descriptor()
	// menu.DefaultIsBuiltin holds the default value on creation for the is_builtin field.
	menu.DefaultIsBuiltin = menuDescIsBuiltin.Default.(bool)
	// menuDescCreateTime is the schema descriptor for create_time field.
	menuDescCreateTime := menuFields[5].Descriptor()
	// menu.DefaultCreateTime holds the default value on creation for the create_time field.
	menu.DefaultCreateTime = menuDescCreateTime.Default.(func() time.Time)
	// menuDescUpdateTime is the schema descriptor for update_time field.
	menuDescUpdateTime := menuFields[6].Descriptor()
	// menu.DefaultUpdateTime holds the default value on creation for the update_time field.
	menu.DefaultUpdateTime = menuDescUpdateTime.Default.(func() time.Time)
	// menu.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	menu.UpdateDefaultUpdateTime = menuDescUpdateTime.UpdateDefault.(func() time.Time)
	// menuDescID is the schema descriptor for id field.
	menuDescID := menuFields[0].Descriptor()
	// menu.IDValidator is a validator for the "id" field. It is called by the builders before save.
	menu.IDValidator = menuDescID.Validators[0].(func(string) error)
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescName is the schema descriptor for name field.
	roleDescName := roleFields[1].Descriptor()
	// role.NameValidator is a validator for the "name" field. It is called by the builders before save.
	role.NameValidator = roleDescName.Validators[0].(func(string) error)
	// roleDescIsBuiltin is the schema descriptor for is_builtin field.
	roleDescIsBuiltin := roleFields[2].Descriptor()
	// role.DefaultIsBuiltin holds the default value on creation for the is_builtin field.
	role.DefaultIsBuiltin = roleDescIsBuiltin.Default.(bool)
	// roleDescCreateTime is the schema descriptor for create_time field.
	roleDescCreateTime := roleFields[3].Descriptor()
	// role.DefaultCreateTime holds the default value on creation for the create_time field.
	role.DefaultCreateTime = roleDescCreateTime.Default.(func() time.Time)
	// roleDescUpdateTime is the schema descriptor for update_time field.
	roleDescUpdateTime := roleFields[4].Descriptor()
	// role.DefaultUpdateTime holds the default value on creation for the update_time field.
	role.DefaultUpdateTime = roleDescUpdateTime.Default.(func() time.Time)
	// role.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	role.UpdateDefaultUpdateTime = roleDescUpdateTime.UpdateDefault.(func() time.Time)
	// roleDescID is the schema descriptor for id field.
	roleDescID := roleFields[0].Descriptor()
	// role.IDValidator is a validator for the "id" field. It is called by the builders before save.
	role.IDValidator = roleDescID.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescCreateTime is the schema descriptor for create_time field.
	userDescCreateTime := userFields[4].Descriptor()
	// user.DefaultCreateTime holds the default value on creation for the create_time field.
	user.DefaultCreateTime = userDescCreateTime.Default.(func() time.Time)
	// userDescUpdateTime is the schema descriptor for update_time field.
	userDescUpdateTime := userFields[5].Descriptor()
	// user.DefaultUpdateTime holds the default value on creation for the update_time field.
	user.DefaultUpdateTime = userDescUpdateTime.Default.(func() time.Time)
	// user.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	user.UpdateDefaultUpdateTime = userDescUpdateTime.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.IDValidator is a validator for the "id" field. It is called by the builders before save.
	user.IDValidator = userDescID.Validators[0].(func(string) error)
}
