syntax = "proto3";

package v1;

option go_package = "momoko/api/gen/v1;v1";

import "google/api/annotations.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";

// 认证服务
service AuthService {
  // 账号登录
  rpc Login(LoginRequest) returns (LoginResponse) {
    option (google.api.http) = {
      post: "/api/v1/auth/login"
      body: "*"
    };
  }
  // 注册
  rpc Register(RegisterRequest) returns (RegisterResponse) {
    option (google.api.http) = {
      post: "/api/v1/auth/register"
      body: "*"
    };
  }
  // 发送注册邮件验证码
  rpc SendRegisterEmailCode(SendRegisterEmailCodeRequest) returns (SendRegisterEmailCodeResponse) {
    option (google.api.http) = {
      post: "/api/v1/auth/register/email-code"
      body: "*"
    };
  }
  // 发送登录邮件验证码
  rpc SendLoginEmailCode(SendLoginEmailCodeRequest) returns (SendLoginEmailCodeResponse) {
    option (google.api.http) = {
      post: "/api/v1/auth/login/email-code"
      body: "*"
    };
  }
  // 刷新token
  rpc Refresh(RefreshRequest) returns (RefreshResponse) {
    option (google.api.http) = {
      post: "/api/v1/auth/refresh"
      body: "*"
    };
  }
  // 获取登录设备
  rpc Devices(DevicesRequest) returns (DevicesResponse) {
    option (google.api.http) = {
      get: "/api/v1/auth/devices"
    };
  }
  // 更新密码
  rpc UpdatePassword(UpdatePasswordRequest) returns (UpdatePasswordResponse) {
    option (google.api.http) = {
      put: "/api/v1/auth/password"
      body: "*"
    };
  }
  // 退出登录
  rpc Logout(LogoutRequest) returns (LogoutResponse) {
    option (google.api.http) = {
      post: "/api/v1/auth/logout"
      body: "*"
    };
  }
  // 删除已登录的设备
  rpc DelLogin(DelLoginRequest) returns (DelLoginResponse) {
    option (google.api.http) = {
      delete: "/api/v1/auth/devices/{id}"
    };
  }
}

// 账号登录请求
message LoginRequest {
  // 登录密码
  string password = 1;
  // 登录渠道
  oneof identity {
    // 用户名登录
    string username = 2;
    // 邮箱登录
    string email = 3;
  }
  // 登录设备
  string device = 4;
  // 设备码
  string device_id = 5;
  // 邮箱验证码
  string code = 6;
}

// 注册请求
message RegisterRequest {
  // 用户名
  string username = 1;
  // 密码
  string password = 2;
  // 邮箱
  string email = 3;
  // 邮箱验证码
  string code = 4;
}

// 注册响应
message RegisterResponse {
  // 用户id
  string user_id = 1;
}

// 发送注册邮件验证码请求
message SendRegisterEmailCodeRequest {
  // 邮箱
  string email = 1;
}

// 发送注册邮件验证码响应
message SendRegisterEmailCodeResponse {}

// 发送登录邮件验证码请求
message SendLoginEmailCodeRequest {
  // 邮箱
  string email = 1;
}

// 发送登录邮件验证码响应
message SendLoginEmailCodeResponse {}

// 账号登录响应
message LoginResponse {
  // token
  string access_token = 1;
  // 刷新token
  string refresh_token = 2;
  // token 有效时间
  google.protobuf.Duration expires_in = 3;
}

// 刷新token请求
message RefreshRequest {
  // 刷新token
  string refresh_token = 1;
}

// 刷新token响应
message RefreshResponse {
  // token
  string access_token = 1;
  // 刷新token
  string refresh_token = 2;
  // token 有效时间
  google.protobuf.Duration expires_in = 3;
}

// 获取登录设备请求
message DevicesRequest {

}

// 获取登录设备响应
message DevicesResponse {
  // 设备列表
  repeated LoginDevice devices = 1;
  // 当前设备id
  string device_id = 2;
}

// 登录设备信息
message LoginDevice {
  // 登录时间
  google.protobuf.Timestamp login_time = 1;
  // 登录设备
  string device = 2;
  // 登录ip
  string ip = 3;
  // 设备id
  string device_id = 4;
  // 会话id
  string session_id = 5;
  // 最近一次刷新时间
  google.protobuf.Timestamp update_time = 6;
}

// 更新密码请求
message UpdatePasswordRequest {
  // 旧密码
  string old_password = 1;
  // 新密码
  string new_password = 2;
}

// 更新密码响应
message UpdatePasswordResponse {}

// 退出登录请求
message LogoutRequest{}

// 退出登录响应
message LogoutResponse{}

// 删除已登录的设备请求
message DelLoginRequest{
  // 设备id
  string id = 1;
}

// 删除已登录的设备响应
message DelLoginResponse{}
