syntax = "proto3";

package v1;

option go_package = "momoko/api/gen/v1;v1";

import "google/api/annotations.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";

// 认证服务
service AuthService {
  // 账号登录
  rpc Login(LoginRequest) returns (LoginResponse) {
    option (google.api.http) = {
      post: "/api/v1/auth/login"
      body: "*"
    };
  }
  // 刷新token
  rpc Refresh(RefreshRequest) returns (RefreshResponse) {
    option (google.api.http) = {
      post: "/api/v1/auth/refresh"
      body: "*"
    };
  }
  // 获取登录设备
  rpc Devices(DevicesRequest) returns (DevicesResponse) {
    option (google.api.http) = {
      get: "/api/v1/auth/devices"
    };
  }
}

// 账号登录请求
message LoginRequest {
  // 登录密码
  string password = 1;
  // 登录渠道
  oneof identity {
    // 用户名登录
    string username = 2;
    // 邮箱登录
    string email = 3;
  }
  // 登录设备
  string device = 4;
  // ip地址
  string ip = 5;
  // 设备码
  string device_id = 6;
}

// 账号登录响应
message LoginResponse {
  // token
  string access_token = 1;
  // 刷新token
  string refresh_token = 2;
  // token 有效时间
  google.protobuf.Duration expires_in = 3;
}

// 刷新token请求
message RefreshRequest {
  // 刷新token
  string refresh_token = 1;
}

// 刷新token响应
message RefreshResponse {
  // token
  string access_token = 1;
  // 刷新token
  string refresh_token = 2;
  // token 有效时间
  google.protobuf.Duration expires_in = 3;
}

// 获取登录设备请求
message DevicesRequest {

}

// 获取登录设备响应
message DevicesResponse {
  // 设备列表
  repeated LoginDevice devices = 1;
  // 当前设备id
  string device_id = 2;
}

// 登录设备信息
message LoginDevice {
  // 登录时间
  google.protobuf.Timestamp login_time = 1;
  // 登录设备
  string device = 2;
  // 登录ip
  string ip = 3;
  // 设备id
  string device_id = 4;
  // 会话id
  string session_id = 5;
  // 最近一次刷新时间
  google.protobuf.Timestamp update_time = 6;
}