syntax = "proto3";

package v1;

option go_package = "momoko/api/gen/v1;v1";

import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";

// 应用管理
service InstanceManager {
  // 实例类型管理
  // 获取实例类型
  rpc GetInstanceTypes(GetInstanceTypesRequest) returns (GetInstanceTypesResponse) {
    option (google.api.http) = {
      get: "/api/v1/instance/type"
    };
  }
  // 创建实例类型
  rpc CreateInstanceType(CreateInstanceTypeRequest) returns (CreateInstanceTypeResponse) {
    option (google.api.http) = {
      post: "/api/v1/instance/type"
      body: "*"
    };
  }
  // 更新实例类型
  rpc UpdateInstanceType(UpdateInstanceTypeRequest) returns (UpdateInstanceTypeResponse) {
    option (google.api.http) = {
      put: "/api/v1/instance/type/{id}"
      body: "*"
    };
  }
  // 删除实例类型
  rpc DelInstanceType(DelInstanceTypeRequest) returns (DelInstanceTypeResponse) {
    option (google.api.http) = {
      delete: "/api/v1/instance/type/{id}"
    };
  }

  // 终端管理
  // 获取终端详情
  rpc GetTerminalInfo(GetTerminalInfoRequest) returns (GetTerminalInfoResponse){
    option (google.api.http) = {
      get: "/api/v1/instance/terminal"
    };
  }
  // 启动终端
  rpc StartTerminal(StartTerminalRequest) returns (StartTerminalResponse) {
    option (google.api.http) = {
      post: "/api/v1/instance/terminal/start"
      body: "*"
    };
  }
  // 停止终端
  rpc StopTerminal(StopTerminalRequest) returns (StopTerminalResponse) {
    option (google.api.http) = {
      post: "/api/v1/instance/terminal/stop"
      body: "*"
    };
  }
  // 重启终端
  rpc RestartTerminal(RestartTerminalRequest) returns (RestartTerminalResponse) {
    option (google.api.http) = {
      post: "/api/v1/instance/terminal/restart"
      body: "*"
    };
  }


  // 实例管理
  // 获取实例列表
  rpc GetInstances(GetInstancesRequest) returns (GetInstancesResponse) {
    option (google.api.http) = {
      get: "/api/v1/instance"
    };
  }
  // 创建实例
  rpc CreateInstance(CreateInstanceRequest) returns (CreateInstanceResponse) {
    option (google.api.http) = {
      post: "/api/v1/instance"
      body: "*"
    };
  }
  // 获取实例详情
  rpc GetInstanceInfo(GetInstanceInfoRequest) returns (GetInstanceInfoResponse) {
    option (google.api.http) = {
      get: "/api/v1/instance/{id}"
    };
  }
  // 启动实例
  rpc StartInstance(StartInstanceRequest) returns (StartInstanceResponse) {
    option (google.api.http) = {
      post: "/api/v1/instance/instance/start/{id}"
      body: "*"
    };
  }
  // 停止实例
  rpc StopInstance(StopInstanceRequest) returns (StopInstanceResponse) {
    option (google.api.http) = {
      post: "/api/v1/instance/instance/stop/{id}"
      body: "*"
    };
  }
  // 重启实例
  rpc RestartInstance(RestartInstanceRequest) returns (RestartInstanceResponse) {
    option (google.api.http) = {
      post: "/api/v1/instance/instance/restart/{id}"
      body: "*"
    };
  }
  // 删除实例
  rpc DelInstance(DelInstanceRequest) returns (DelInstanceResponse) {
    option (google.api.http) = {
      delete: "/api/v1/instance/instance/del/{id}"
    };
  }
  // 更新实例
  rpc UpdateInstance(UpdateInstanceRequest) returns (UpdateInstanceResponse) {
    option (google.api.http) = {
      put: "/api/v1/instance/instance/{id}"
      body: "*"
    };
  }
}

// 获取实例类型请求
message GetInstanceTypesRequest {}

// 获取实例类型响应
message GetInstanceTypesResponse {
  // 类型列表
  repeated InstanceTypeInfo types = 1;
}

// 创建实例类型请求
message CreateInstanceTypeRequest {
  // 类型名称
  string name = 1;
}

// 创建实例类型响应
message CreateInstanceTypeResponse {
  // 实例信息
  InstanceTypeInfo type = 1;
}

// 更新实例类型请求
message UpdateInstanceTypeRequest {
  // 类型id
  string id = 1;
  // 类型名称
  optional string name = 2;
  // 是否启用
  optional bool is_enable = 3;
}

// 更新实例类型响应
message UpdateInstanceTypeResponse {
  // 实例信息
  InstanceTypeInfo type = 1;
}

// 删除实例类型请求
message DelInstanceTypeRequest {
  // 类型id
  string id = 1;
}

// 删除实例类型响应
message DelInstanceTypeResponse {}

// 实例类型信息
message InstanceTypeInfo {
  // 类型id
  string id = 1;
  // 类型名称
  string name = 2;
  // 是否系统内置
  bool is_system = 3;
  // 是否启用
  bool is_enable = 4;
}

// 获取终端详情请求
message GetTerminalInfoRequest {}

// 获取终端详情响应
message GetTerminalInfoResponse {
  // 信息
  InstanceInfo info = 1;
}

// 启动终端请求
message StartTerminalRequest {}

// 启动终端响应
message StartTerminalResponse {}

// 停止终端请求
message StopTerminalRequest {}

// 停止终端响应
message StopTerminalResponse {}

// 重启终端请求
message RestartTerminalRequest{}

// 重启终端响应
message RestartTerminalResponse{}

// 获取实例列表请求
message GetInstancesRequest{
  // page
  int64 page = 1;
  // page size
  int64 page_size = 2;
  // 实例名称/标签
  optional string keywords = 3;
  // 类型
  optional string type = 4;
  // 状态
  optional InstanceStatus status = 5;
}

// 获取实例列表响应
message GetInstancesResponse{
  // actual page
  int64 page = 1;
  // actual page size
  int64 page_size = 2;
  // 总数
  int64 total = 3;
  // 列表
  repeated InstanceInfo infos = 4;
}

// 创建实例请求
message CreateInstanceRequest {
  // 实例名称
  string name = 1;
  // 备注
  string remark = 2;
  // 标签(,号隔开)
  string tags = 3;
  // 类型
  string type = 4;
  // 所属用户id
  string user_id = 5;
  // 启动命令
  string start_command = 6;
  // 实例路径
  string instance_path = 7;
  // 停止命令
  string stop_command = 8;
  // 是否自启动
  bool auto_start = 9;
  // 环境变量(一行一个 如:GO_WANT_HELPER_PROCESS=1
  repeated string env = 10;
}

// 创建实例响应
message CreateInstanceResponse {
  // 实例详情
  InstanceInfo info = 1;
}

// 获取实例详情请求
message GetInstanceInfoRequest{
  // id
  string id = 1;
}

// 获取实例详情响应
message GetInstanceInfoResponse{
  // 实例详情
  InstanceInfo info = 1;
}

// 获取实例控制台详情请求
message GetInstanceTerminalInfoRequest {
  // 实例id
  string id = 1;
}

// 获取实例控制台详情响应
message GetInstanceTerminalInfoResponse {

}

// 启动实例请求
message StartInstanceRequest {
  // 实例id
  string id = 1;
}

// 启动实例响应
message StartInstanceResponse {
  // 实例详情
  InstanceInfo info = 1;
}

// 停止实例请求
message StopInstanceRequest {
  // 实例id
  string id = 1;
}

// 停止实例响应
message StopInstanceResponse {}

// 重启实例请求
message RestartInstanceRequest {
  // 实例id
  string id = 1;
}

// 重启实例响应
message RestartInstanceResponse {}

// 删除实例请求
message DelInstanceRequest {
  // 实例id
  string id = 1;
}

// 删除实例响应
message DelInstanceResponse {}

message UpdateInstanceRequest{
  // 实例id
  string id = 1;
  // 实例名称
  optional string name = 2;
  // 备注
  optional string remark = 3;
  // 标签(,号隔开)
  optional string tags = 4;
  // 类型
  optional string type = 5;
  // 所属用户id
  optional string user_id = 6;
  // 启动命令
  optional string start_command = 7;
  // 实例路径
  optional string instance_path = 8;
  // ws路径(启动时才有
  optional string ws_path = 9;
  // 停止命令
  optional string stop_command = 10;
  // 是否自启动
  optional bool auto_start = 11;
  // 环境变量(一行一个 如:GO_WANT_HELPER_PROCESS=1
  repeated string env = 12;
}

message UpdateInstanceResponse{
  // 实例详情
  InstanceInfo info = 1;
}

// 实例详情
message InstanceInfo {
  // 实例id
  string id = 1;
  // 实例名称
  string name = 2;
  // 实例状态
  InstanceStatus status = 3;
  // 启动时间
  google.protobuf.Timestamp start_time = 4;
  // 创建时间
  google.protobuf.Timestamp create_time = 5;
  // 备注
  string remark = 6;
  // 标签(,号隔开)
  string tags = 7;
  // 类型
  string type = 8;
  // 所属用户id
  string user_id = 9;
  // 启动命令
  string start_command = 10;
  // 实例路径
  string instance_path = 11;
  // ws路径(启动时才有
  string ws_path = 12;
  // 停止命令
  string stop_command = 13;
  // 是否自启动
  bool auto_start = 14;
  // 环境变量(一行一个 如:GO_WANT_HELPER_PROCESS=1
  repeated string env = 15;
}

// 实例状态
enum InstanceStatus {
  // 未指定
  INSTANCE_STATUS_UNSPECIFIED = 0;
  // 停止
  INSTANCE_STATUS_STOPPED = 1;
  // 运行中
  INSTANCE_STATUS_RUNNING = 2;
  // 维护
  INSTANCE_STATUS_MAINTENANCE = 3;
}
