syntax = "proto3";

package v1;

option go_package = "momoko/api/gen/v1;v1";

import "google/api/annotations.proto";
import "google/protobuf/timestamp.proto";

// 应用管理
service ServerManager {
  // 终端管理
  // 获取终端详情
  rpc GetTerminalInfo(GetTerminalInfoRequest) returns (GetTerminalInfoResponse){
    option (google.api.http) = {
      get: "/api/v1/server/terminal"
    };
  }
  // 启动/停止/重启 终端

  // 实例管理
  // 获取实例列表
  // 获取实例详情
  // 启动/停止/重启 实例
}

// 获取终端详情请求
message GetTerminalInfoRequest {}

// 获取终端详情响应
message GetTerminalInfoResponse {

}