// Code generated by ent, DO NOT EDIT.

package fileuploadchunk

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the fileuploadchunk type in the database.
	Label = "file_upload_chunk"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldUploadID holds the string denoting the upload_id field in the database.
	FieldUploadID = "upload_id"
	// FieldChunk holds the string denoting the chunk field in the database.
	FieldChunk = "chunk"
	// FieldHash holds the string denoting the hash field in the database.
	FieldHash = "hash"
	// FieldSize holds the string denoting the size field in the database.
	FieldSize = "size"
	// EdgeUpload holds the string denoting the upload edge name in mutations.
	EdgeUpload = "upload"
	// Table holds the table name of the fileuploadchunk in the database.
	Table = "file_upload_chunks"
	// UploadTable is the table that holds the upload relation/edge.
	UploadTable = "file_upload_chunks"
	// UploadInverseTable is the table name for the FileUpload entity.
	// It exists in this package in order to avoid circular dependency with the "fileupload" package.
	UploadInverseTable = "file_uploads"
	// UploadColumn is the table column denoting the upload relation/edge.
	UploadColumn = "upload_id"
)

// Columns holds all SQL columns for fileuploadchunk fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldUploadID,
	FieldChunk,
	FieldHash,
	FieldSize,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
)

// OrderOption defines the ordering options for the FileUploadChunk queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByUploadID orders the results by the upload_id field.
func ByUploadID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUploadID, opts...).ToFunc()
}

// ByChunk orders the results by the chunk field.
func ByChunk(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChunk, opts...).ToFunc()
}

// ByHash orders the results by the hash field.
func ByHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHash, opts...).ToFunc()
}

// BySize orders the results by the size field.
func BySize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSize, opts...).ToFunc()
}

// ByUploadField orders the results by upload field.
func ByUploadField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUploadStep(), sql.OrderByField(field, opts...))
	}
}
func newUploadStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UploadInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, UploadTable, UploadColumn),
	)
}
