// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.0
// source: v1/docker.proto

/* eslint-disable */

export const protobufPackage = "v1";

/** Docker连接状态请求 */
export interface DockerStatusRequest {
}

/** Docker连接状态响应 */
export interface DockerStatusResponse {
  /** 是否启用 */
  enabled: boolean;
  /** 是否已连接 */
  connected: boolean;
  /** 错误信息 */
  error: string;
  /** 引擎信息 */
  info:
    | DockerEngineInfo
    | undefined;
  /** 版本信息 */
  version: DockerEngineVersion | undefined;
}

/** Docker引擎信息 */
export interface DockerEngineInfo {
  /** 引擎ID */
  id: string;
  /** 主机名称 */
  name: string;
  /** 服务端版本 */
  serverVersion: string;
  /** 操作系统 */
  operatingSystem: string;
  /** 操作系统类型 */
  osType: string;
  /** CPU架构 */
  architecture: string;
  /** Docker根目录 */
  dockerRootDir: string;
  /** 容器总数 */
  containers: number;
  /** 运行中容器数 */
  containersRunning: number;
  /** 暂停容器数 */
  containersPaused: number;
  /** 停止容器数 */
  containersStopped: number;
  /** 镜像数量 */
  images: number;
  /** 存储驱动 */
  driver: string;
  /** cgroup驱动 */
  cgroupDriver: string;
  /** cgroup版本 */
  cgroupVersion: string;
  /** 内存总量 */
  memoryTotal: number;
  /** CPU数量 */
  cpus: number;
  /** 标签 */
  labels: string[];
}

/** Docker引擎版本 */
export interface DockerEngineVersion {
  /** Docker版本 */
  version: string;
  /** API版本 */
  apiVersion: string;
  /** 最低API版本 */
  minApiVersion: string;
  /** Git提交 */
  gitCommit: string;
  /** Go版本 */
  goVersion: string;
  /** 操作系统 */
  os: string;
  /** CPU架构 */
  arch: string;
  /** 内核版本 */
  kernelVersion: string;
  /** 构建时间 */
  buildTime: string;
}

/** 获取Docker配置请求 */
export interface GetDockerConfigRequest {
}

/** 获取Docker配置响应 */
export interface GetDockerConfigResponse {
  /** Docker配置 */
  config: DockerConfigInfo | undefined;
}

/** 更新Docker配置请求 */
export interface UpdateDockerConfigRequest {
  /** Docker配置 */
  config: DockerConfigInfo | undefined;
}

/** 更新Docker配置响应 */
export interface UpdateDockerConfigResponse {
  /** Docker配置 */
  config: DockerConfigInfo | undefined;
}

/** 测试Docker配置请求 */
export interface TestDockerConfigRequest {
  /** Docker配置 */
  config: DockerConfigInfo | undefined;
}

/** 测试Docker配置响应 */
export interface TestDockerConfigResponse {
  /** 连接状态 */
  status: DockerStatusResponse | undefined;
}

/** Docker配置 */
export interface DockerConfigInfo {
  /** 是否启用 */
  enabled: boolean;
  /** Docker连接地址 */
  host: string;
  /** 是否启用TLS */
  tlsEnabled: boolean;
  /** CA证书路径 */
  tlsCaPath: string;
  /** 客户端证书路径 */
  tlsCertPath: string;
  /** 客户端私钥路径 */
  tlsKeyPath: string;
  /** API版本 */
  apiVersion: string;
  /** 请求超时秒数 */
  requestTimeoutSeconds: number;
  /** 默认平台 */
  defaultPlatform: string;
  /** 默认日志行数 */
  defaultLogTail: number;
  /** 任务超时秒数 */
  taskTimeoutSeconds: number;
  /** 仓库认证配置 */
  registryAuths: DockerRegistryAuth[];
}

/** Docker仓库认证 */
export interface DockerRegistryAuth {
  /** 仓库地址 */
  serverAddress: string;
  /** 用户名 */
  username: string;
  /** 密码 */
  password: string;
  /** Token */
  token: string;
}

/** 获取Docker任务列表请求 */
export interface ListDockerTasksRequest {
}

/** 获取Docker任务列表响应 */
export interface ListDockerTasksResponse {
  /** 任务列表 */
  tasks: DockerTaskInfo[];
}

/** 获取Docker任务详情请求 */
export interface GetDockerTaskRequest {
  /** 任务ID */
  taskId: string;
}

/** 获取Docker任务详情响应 */
export interface GetDockerTaskResponse {
  /** 任务详情 */
  task: DockerTaskInfo | undefined;
}

/** Docker任务 */
export interface DockerTaskInfo {
  /** 任务ID */
  id: string;
  /** 任务类型 */
  type: string;
  /** 任务状态 */
  status: string;
  /** 进度信息 */
  progress: string;
  /** 消息 */
  message: string;
  /** 错误信息 */
  error: string;
  /** 结果路径 */
  resultPath: string;
  /** 开始时间 */
  startTime:
    | Date
    | undefined;
  /** 结束时间 */
  endTime:
    | Date
    | undefined;
  /** 任务事件 */
  events: DockerTaskEvent[];
}

/** Docker任务事件 */
export interface DockerTaskEvent {
  /** 事件时间 */
  time:
    | Date
    | undefined;
  /** 状态 */
  status: string;
  /** 进度 */
  progress: string;
  /** 事件ID */
  id: string;
  /** 消息 */
  message: string;
  /** 错误信息 */
  error: string;
}

/** 获取容器列表请求 */
export interface ListDockerContainersRequest {
  /** 是否包含停止容器 */
  all: boolean;
  /** 状态筛选 */
  status: string;
  /** 名称筛选 */
  name: string;
  /** 镜像筛选 */
  image: string;
  /** 网络筛选 */
  network: string;
  /** 标签筛选 */
  labels: { [key: string]: string };
  /** 页码 */
  page: number;
  /** 每页数量 */
  pageSize: number;
}

export interface ListDockerContainersRequest_LabelsEntry {
  key: string;
  value: string;
}

/** 获取容器列表响应 */
export interface ListDockerContainersResponse {
  /** 容器列表 */
  items: DockerContainerSummary[];
  /** 总数 */
  total: number;
}

/** 获取容器详情请求 */
export interface GetDockerContainerRequest {
  /** 容器ID或名称 */
  id: string;
}

/** 获取容器详情响应 */
export interface GetDockerContainerResponse {
  /** 容器详情 */
  info: DockerContainerInfo | undefined;
}

/** 创建容器请求 */
export interface CreateDockerContainerRequest {
  /** 创建参数 */
  options: DockerContainerCreateOptions | undefined;
}

/** 创建容器响应 */
export interface CreateDockerContainerResponse {
  /** 容器ID */
  id: string;
}

/** 更新容器请求 */
export interface UpdateDockerContainerRequest {
  /** 容器ID或名称 */
  id: string;
  /** 容器名称 */
  name: string;
  /** 重启策略 */
  restartPolicy: string;
  /** 内存限制 */
  memory: number;
  /** swap限制 */
  memorySwap: number;
  /** CPU权重 */
  cpuShares: number;
  /** CPU配额 */
  cpuQuota: number;
  /** CPU周期 */
  cpuPeriod: number;
  /** Nano CPU数量 */
  nanoCpus: number;
  /** 完整重建参数 */
  options:
    | DockerContainerCreateOptions
    | undefined;
  /** 是否通过重建完成编辑 */
  recreate: boolean;
  /** 是否强制删除旧容器 */
  force: boolean;
  /** 是否删除匿名卷 */
  removeVolumes: boolean;
}

/** 更新容器响应 */
export interface UpdateDockerContainerResponse {
  /** 容器详情 */
  info:
    | DockerContainerInfo
    | undefined;
  /** 重建任务 */
  task: DockerTaskInfo | undefined;
}

/** 重建容器请求 */
export interface RecreateDockerContainerRequest {
  /** 容器ID或名称 */
  id: string;
  /** 创建参数 */
  options:
    | DockerContainerCreateOptions
    | undefined;
  /** 是否强制删除旧容器 */
  force: boolean;
  /** 是否删除匿名卷 */
  removeVolumes: boolean;
}

/** 重建容器响应 */
export interface RecreateDockerContainerResponse {
  /** 任务 */
  task: DockerTaskInfo | undefined;
}

/** 启动容器请求 */
export interface StartDockerContainerRequest {
  /** 容器ID或名称 */
  id: string;
}

/** 启动容器响应 */
export interface StartDockerContainerResponse {
}

/** 停止容器请求 */
export interface StopDockerContainerRequest {
  /** 容器ID或名称 */
  id: string;
  /** 超时秒数 */
  timeoutSeconds: number;
}

/** 停止容器响应 */
export interface StopDockerContainerResponse {
}

/** 重启容器请求 */
export interface RestartDockerContainerRequest {
  /** 容器ID或名称 */
  id: string;
  /** 超时秒数 */
  timeoutSeconds: number;
}

/** 重启容器响应 */
export interface RestartDockerContainerResponse {
}

/** 强制停止容器请求 */
export interface KillDockerContainerRequest {
  /** 容器ID或名称 */
  id: string;
  /** 信号 */
  signal: string;
}

/** 强制停止容器响应 */
export interface KillDockerContainerResponse {
}

/** 暂停容器请求 */
export interface PauseDockerContainerRequest {
  /** 容器ID或名称 */
  id: string;
}

/** 暂停容器响应 */
export interface PauseDockerContainerResponse {
}

/** 恢复容器请求 */
export interface UnpauseDockerContainerRequest {
  /** 容器ID或名称 */
  id: string;
}

/** 恢复容器响应 */
export interface UnpauseDockerContainerResponse {
}

/** 重命名容器请求 */
export interface RenameDockerContainerRequest {
  /** 容器ID或名称 */
  id: string;
  /** 新名称 */
  name: string;
}

/** 重命名容器响应 */
export interface RenameDockerContainerResponse {
}

/** 删除容器请求 */
export interface DeleteDockerContainerRequest {
  /** 容器ID或名称 */
  id: string;
  /** 是否强制删除 */
  force: boolean;
  /** 是否删除匿名卷 */
  removeVolumes: boolean;
}

/** 删除容器响应 */
export interface DeleteDockerContainerResponse {
}

/** 获取容器日志请求 */
export interface ContainerLogsRequest {
  /** 容器ID或名称 */
  id: string;
  /** 是否显示stdout */
  stdout: boolean;
  /** 是否显示stderr */
  stderr: boolean;
  /** 起始时间 */
  since: string;
  /** 结束时间 */
  until: string;
  /** 是否显示时间戳 */
  timestamps: boolean;
  /** 尾部行数 */
  tail: string;
  /** 是否显示详情 */
  details: boolean;
}

/** 获取容器日志响应 */
export interface ContainerLogsResponse {
  /** 日志内容 */
  logs: string;
}

/** 获取容器资源状态请求 */
export interface ContainerStatsRequest {
  /** 容器ID或名称 */
  id: string;
}

/** 获取容器资源状态响应 */
export interface ContainerStatsResponse {
  /** 原始状态JSON */
  json: string;
}

/** 创建容器执行会话请求 */
export interface CreateContainerExecRequest {
  /** 容器ID或名称 */
  containerId: string;
  /** 执行命令 */
  cmd: string[];
  /** 环境变量 */
  env: string[];
  /** 用户 */
  user: string;
  /** 工作目录 */
  workingDir: string;
  /** 是否开启TTY */
  tty: boolean;
}

/** 创建容器执行会话响应 */
export interface CreateContainerExecResponse {
  /** 执行会话ID */
  execId: string;
}

/** 容器创建参数 */
export interface DockerContainerCreateOptions {
  /** 容器名称 */
  name: string;
  /** 镜像 */
  image: string;
  /** 主机名 */
  hostname: string;
  /** 用户 */
  user: string;
  /** 环境变量 */
  env: string[];
  /** 启动命令 */
  cmd: string[];
  /** 入口命令 */
  entrypoint: string[];
  /** 工作目录 */
  workingDir: string;
  /** 标签 */
  labels: { [key: string]: string };
  /** 是否开启TTY */
  tty: boolean;
  /** 是否打开stdin */
  openStdin: boolean;
  /** 网络名称 */
  network: string;
  /** 重启策略 */
  restartPolicy: string;
  /** 是否自动删除 */
  autoRemove: boolean;
  /** 是否特权模式 */
  privileged: boolean;
  /** 端口映射 */
  ports: DockerPortBinding[];
  /** 挂载配置 */
  mounts: DockerMount[];
  /** 内存限制 */
  memory: number;
  /** swap限制 */
  memorySwap: number;
  /** CPU权重 */
  cpuShares: number;
  /** CPU配额 */
  cpuQuota: number;
  /** CPU周期 */
  cpuPeriod: number;
  /** Nano CPU数量 */
  nanoCpus: number;
  /** 平台 */
  platform: string;
}

export interface DockerContainerCreateOptions_LabelsEntry {
  key: string;
  value: string;
}

/** 容器摘要 */
export interface DockerContainerSummary {
  /** 容器ID */
  id: string;
  /** 容器名称 */
  names: string[];
  /** 镜像 */
  image: string;
  /** 镜像ID */
  imageId: string;
  /** 命令 */
  command: string;
  /** 创建时间 */
  created:
    | Date
    | undefined;
  /** 状态 */
  state: string;
  /** 状态描述 */
  status: string;
  /** 标签 */
  labels: { [key: string]: string };
  /** 端口 */
  ports: DockerPort[];
  /** 挂载点 */
  mounts: DockerMountPoint[];
  /** 网络模式 */
  networkMode: string;
  /** 网络 */
  networks: string[];
}

export interface DockerContainerSummary_LabelsEntry {
  key: string;
  value: string;
}

/** 容器详情 */
export interface DockerContainerInfo {
  /** 容器ID */
  id: string;
  /** 容器名称 */
  name: string;
  /** 镜像 */
  image: string;
  /** 镜像ID */
  imageId: string;
  /** 启动路径 */
  path: string;
  /** 启动参数 */
  args: string[];
  /** 创建时间 */
  created: string;
  /** 状态 */
  state:
    | DockerContainerState
    | undefined;
  /** 容器配置 */
  config:
    | { [key: string]: any }
    | undefined;
  /** 主机配置 */
  hostConfig:
    | { [key: string]: any }
    | undefined;
  /** 网络配置 */
  network:
    | { [key: string]: any }
    | undefined;
  /** 挂载点 */
  mounts: DockerMountPoint[];
  /** 重启次数 */
  restartCount: number;
  /** 平台 */
  platform: string;
  /** 存储驱动 */
  driver: string;
  /** 日志路径 */
  logPath: string;
}

/** 容器状态 */
export interface DockerContainerState {
  /** 状态 */
  status: string;
  /** 是否运行中 */
  running: boolean;
  /** 是否暂停 */
  paused: boolean;
  /** 是否重启中 */
  restarting: boolean;
  /** 是否OOM */
  oomKilled: boolean;
  /** 是否已死亡 */
  dead: boolean;
  /** 进程ID */
  pid: number;
  /** 退出码 */
  exitCode: number;
  /** 错误信息 */
  error: string;
  /** 启动时间 */
  startedAt: string;
  /** 结束时间 */
  finishedAt: string;
}

/** 端口 */
export interface DockerPort {
  /** IP地址 */
  ip: string;
  /** 容器端口 */
  privatePort: number;
  /** 主机端口 */
  publicPort: number;
  /** 协议类型 */
  type: string;
}

/** 端口映射 */
export interface DockerPortBinding {
  /** 容器端口 */
  containerPort: string;
  /** 主机IP */
  hostIp: string;
  /** 主机端口 */
  hostPort: string;
}

/** 挂载配置 */
export interface DockerMount {
  /** 挂载类型 */
  type: string;
  /** 来源 */
  source: string;
  /** 目标路径 */
  target: string;
  /** 是否只读 */
  readOnly: boolean;
}

/** 挂载点 */
export interface DockerMountPoint {
  /** 挂载类型 */
  type: string;
  /** 名称 */
  name: string;
  /** 来源 */
  source: string;
  /** 目标路径 */
  destination: string;
  /** 驱动 */
  driver: string;
  /** 模式 */
  mode: string;
  /** 是否可写 */
  rw: boolean;
  /** 传播模式 */
  propagation: string;
}

/** 获取镜像列表请求 */
export interface ListDockerImagesRequest {
  /** 是否包含中间镜像 */
  all: boolean;
  /** 是否悬空 */
  dangling?:
    | boolean
    | undefined;
  /** 关键字 */
  keyword: string;
  /** 标签筛选 */
  labels: { [key: string]: string };
  /** 页码 */
  page: number;
  /** 每页数量 */
  pageSize: number;
}

export interface ListDockerImagesRequest_LabelsEntry {
  key: string;
  value: string;
}

/** 获取镜像列表响应 */
export interface ListDockerImagesResponse {
  /** 镜像列表 */
  items: DockerImageSummary[];
  /** 总数 */
  total: number;
}

/** 获取镜像详情请求 */
export interface GetDockerImageRequest {
  /** 镜像ID或名称 */
  id: string;
}

/** 获取镜像详情响应 */
export interface GetDockerImageResponse {
  /** 镜像详情 */
  info: DockerImageInfo | undefined;
}

/** 拉取镜像请求 */
export interface PullDockerImageRequest {
  /** 镜像引用 */
  reference: string;
  /** 平台 */
  platform: string;
  /** 仓库认证 */
  registryAuth: DockerRegistryAuth | undefined;
}

/** 拉取镜像响应 */
export interface PullDockerImageResponse {
  /** 任务 */
  task: DockerTaskInfo | undefined;
}

/** 构建镜像请求 */
export interface BuildDockerImageRequest {
  /** 上下文路径 */
  contextPath: string;
  /** Dockerfile路径 */
  dockerfile: string;
  /** 镜像标签 */
  tags: string[];
  /** 构建参数 */
  buildArgs: { [key: string]: string };
  /** 标签 */
  labels: { [key: string]: string };
  /** 平台 */
  platform: string;
  /** 是否禁用缓存 */
  noCache: boolean;
  /** 是否拉取父镜像 */
  pullParent: boolean;
  /** 是否删除中间容器 */
  remove: boolean;
  /** 是否强制删除中间容器 */
  forceRemove: boolean;
}

export interface BuildDockerImageRequest_BuildArgsEntry {
  key: string;
  value: string;
}

export interface BuildDockerImageRequest_LabelsEntry {
  key: string;
  value: string;
}

/** 构建镜像响应 */
export interface BuildDockerImageResponse {
  /** 任务 */
  task: DockerTaskInfo | undefined;
}

/** 更新镜像标签请求 */
export interface UpdateDockerImageTagsRequest {
  /** 镜像ID */
  imageId: string;
  /** 新增标签 */
  addTags: string[];
  /** 删除标签 */
  deleteTags: string[];
  /** 是否强制删除标签 */
  forceDelete: boolean;
}

/** 更新镜像标签响应 */
export interface UpdateDockerImageTagsResponse {
  /** 镜像详情 */
  info: DockerImageInfo | undefined;
}

/** 给镜像打标签请求 */
export interface TagDockerImageRequest {
  /** 镜像ID */
  id: string;
  /** 目标标签 */
  target: string;
}

/** 给镜像打标签响应 */
export interface TagDockerImageResponse {
}

/** 删除镜像请求 */
export interface DeleteDockerImageRequest {
  /** 镜像ID或标签 */
  id: string;
  /** 是否强制删除 */
  force: boolean;
  /** 是否清理子镜像 */
  pruneChildren: boolean;
}

/** 删除镜像响应 */
export interface DeleteDockerImageResponse {
}

/** 清理镜像请求 */
export interface PruneDockerImagesRequest {
  /** 是否只清理悬空镜像 */
  danglingOnly: boolean;
}

/** 清理镜像响应 */
export interface PruneDockerImagesResponse {
  /** 任务 */
  task: DockerTaskInfo | undefined;
}

/** 获取镜像历史请求 */
export interface ImageHistoryRequest {
  /** 镜像ID或名称 */
  id: string;
}

/** 获取镜像历史响应 */
export interface ImageHistoryResponse {
  /** 历史记录 */
  items: DockerImageHistoryItem[];
}

/** 镜像摘要 */
export interface DockerImageSummary {
  /** 镜像ID */
  id: string;
  /** 仓库标签 */
  repoTags: string[];
  /** 仓库摘要 */
  repoDigests: string[];
  /** 父镜像ID */
  parentId: string;
  /** 创建时间 */
  created:
    | Date
    | undefined;
  /** 大小 */
  size: number;
  /** 共享大小 */
  sharedSize: number;
  /** 使用容器数 */
  containers: number;
  /** 标签 */
  labels: { [key: string]: string };
}

export interface DockerImageSummary_LabelsEntry {
  key: string;
  value: string;
}

/** 镜像详情 */
export interface DockerImageInfo {
  /** 镜像ID */
  id: string;
  /** 仓库标签 */
  repoTags: string[];
  /** 仓库摘要 */
  repoDigests: string[];
  /** 父镜像 */
  parent: string;
  /** 创建时间 */
  created: string;
  /** 作者 */
  author: string;
  /** CPU架构 */
  architecture: string;
  /** 操作系统 */
  os: string;
  /** 大小 */
  size: number;
  /** 虚拟大小 */
  virtualSize: number;
  /** 标签 */
  labels: { [key: string]: string };
  /** 层信息 */
  layers: string[];
}

export interface DockerImageInfo_LabelsEntry {
  key: string;
  value: string;
}

/** 镜像历史记录 */
export interface DockerImageHistoryItem {
  /** 记录ID */
  id: string;
  /** 创建时间 */
  created:
    | Date
    | undefined;
  /** 创建命令 */
  createdBy: string;
  /** 标签 */
  tags: string[];
  /** 大小 */
  size: number;
  /** 备注 */
  comment: string;
}

/** 获取网络列表请求 */
export interface ListDockerNetworksRequest {
  /** 名称筛选 */
  name: string;
  /** 驱动筛选 */
  driver: string;
  /** 作用域筛选 */
  scope: string;
  /** 标签筛选 */
  labels: { [key: string]: string };
  /** 页码 */
  page: number;
  /** 每页数量 */
  pageSize: number;
}

export interface ListDockerNetworksRequest_LabelsEntry {
  key: string;
  value: string;
}

/** 获取网络列表响应 */
export interface ListDockerNetworksResponse {
  /** 网络列表 */
  items: DockerNetworkInfo[];
  /** 总数 */
  total: number;
}

/** 获取网络详情请求 */
export interface GetDockerNetworkRequest {
  /** 网络ID或名称 */
  id: string;
}

/** 获取网络详情响应 */
export interface GetDockerNetworkResponse {
  /** 网络详情 */
  info: DockerNetworkInfo | undefined;
}

/** 创建网络请求 */
export interface CreateDockerNetworkRequest {
  /** 创建参数 */
  options: DockerNetworkCreateOptions | undefined;
}

/** 创建网络响应 */
export interface CreateDockerNetworkResponse {
  /** 网络ID */
  id: string;
}

/** 更新网络请求 */
export interface UpdateDockerNetworkRequest {
  /** 网络ID或名称 */
  id: string;
  /** 标签 */
  labels: { [key: string]: string };
  /** 网络创建参数 */
  options:
    | DockerNetworkCreateOptions
    | undefined;
  /** 是否强制重建 */
  force: boolean;
}

export interface UpdateDockerNetworkRequest_LabelsEntry {
  key: string;
  value: string;
}

/** 更新网络响应 */
export interface UpdateDockerNetworkResponse {
  /** 网络详情 */
  info:
    | DockerNetworkInfo
    | undefined;
  /** 重建任务 */
  task: DockerTaskInfo | undefined;
}

/** 重建网络请求 */
export interface RecreateDockerNetworkRequest {
  /** 网络ID或名称 */
  id: string;
  /** 创建参数 */
  options:
    | DockerNetworkCreateOptions
    | undefined;
  /** 是否强制重建 */
  force: boolean;
}

/** 重建网络响应 */
export interface RecreateDockerNetworkResponse {
  /** 任务 */
  task: DockerTaskInfo | undefined;
}

/** 删除网络请求 */
export interface DeleteDockerNetworkRequest {
  /** 网络ID或名称 */
  id: string;
}

/** 删除网络响应 */
export interface DeleteDockerNetworkResponse {
}

/** 连接容器到网络请求 */
export interface ConnectDockerNetworkRequest {
  /** 网络ID或名称 */
  networkId: string;
  /** 容器ID或名称 */
  containerId: string;
  /** 网络别名 */
  aliases: string[];
  /** 固定IPv4地址 */
  ipv4Address: string;
  /** 固定IPv6地址 */
  ipv6Address: string;
}

/** 连接容器到网络响应 */
export interface ConnectDockerNetworkResponse {
}

/** 断开容器网络请求 */
export interface DisconnectDockerNetworkRequest {
  /** 网络ID或名称 */
  networkId: string;
  /** 容器ID或名称 */
  containerId: string;
  /** 是否强制断开 */
  force: boolean;
}

/** 断开容器网络响应 */
export interface DisconnectDockerNetworkResponse {
}

/** 清理网络请求 */
export interface PruneDockerNetworksRequest {
}

/** 清理网络响应 */
export interface PruneDockerNetworksResponse {
  /** 任务 */
  task: DockerTaskInfo | undefined;
}

/** 网络创建参数 */
export interface DockerNetworkCreateOptions {
  /** 网络名称 */
  name: string;
  /** 网络驱动 */
  driver: string;
  /** 作用域 */
  scope: string;
  /** 是否启用IPv4 */
  enableIpv4?:
    | boolean
    | undefined;
  /** 是否启用IPv6 */
  enableIpv6?:
    | boolean
    | undefined;
  /** 是否内部网络 */
  internal: boolean;
  /** 是否可附加 */
  attachable: boolean;
  /** 是否入口网络 */
  ingress: boolean;
  /** IPAM配置 */
  ipam:
    | DockerIPAM
    | undefined;
  /** 驱动参数 */
  options: { [key: string]: string };
  /** 标签 */
  labels: { [key: string]: string };
}

export interface DockerNetworkCreateOptions_OptionsEntry {
  key: string;
  value: string;
}

export interface DockerNetworkCreateOptions_LabelsEntry {
  key: string;
  value: string;
}

/** 网络详情 */
export interface DockerNetworkInfo {
  /** 网络ID */
  id: string;
  /** 网络名称 */
  name: string;
  /** 创建时间 */
  created: string;
  /** 作用域 */
  scope: string;
  /** 驱动 */
  driver: string;
  /** 是否启用IPv4 */
  enableIpv4: boolean;
  /** 是否启用IPv6 */
  enableIpv6: boolean;
  /** 是否内部网络 */
  internal: boolean;
  /** 是否可附加 */
  attachable: boolean;
  /** 是否入口网络 */
  ingress: boolean;
  /** IPAM配置 */
  ipam:
    | DockerIPAM
    | undefined;
  /** 已连接容器 */
  containers: { [key: string]: DockerNetworkContainer };
  /** 驱动参数 */
  options: { [key: string]: string };
  /** 标签 */
  labels: { [key: string]: string };
}

export interface DockerNetworkInfo_ContainersEntry {
  key: string;
  value: DockerNetworkContainer | undefined;
}

export interface DockerNetworkInfo_OptionsEntry {
  key: string;
  value: string;
}

export interface DockerNetworkInfo_LabelsEntry {
  key: string;
  value: string;
}

/** IPAM配置 */
export interface DockerIPAM {
  /** 驱动 */
  driver: string;
  /** 参数 */
  options: { [key: string]: string };
  /** 地址配置 */
  config: DockerIPAMConfig[];
}

export interface DockerIPAM_OptionsEntry {
  key: string;
  value: string;
}

/** IPAM地址配置 */
export interface DockerIPAMConfig {
  /** 子网 */
  subnet: string;
  /** IP范围 */
  ipRange: string;
  /** 网关 */
  gateway: string;
  /** 辅助地址 */
  auxAddress: { [key: string]: string };
}

export interface DockerIPAMConfig_AuxAddressEntry {
  key: string;
  value: string;
}

/** 网络容器 */
export interface DockerNetworkContainer {
  /** 容器名称 */
  name: string;
  /** 端点ID */
  endpointId: string;
  /** MAC地址 */
  macAddress: string;
  /** IPv4地址 */
  ipv4Address: string;
  /** IPv6地址 */
  ipv6Address: string;
}

/** 获取储存卷列表请求 */
export interface ListDockerVolumesRequest {
  /** 名称筛选 */
  name: string;
  /** 驱动筛选 */
  driver: string;
  /** 标签筛选 */
  labels: { [key: string]: string };
  /** 页码 */
  page: number;
  /** 每页数量 */
  pageSize: number;
}

export interface ListDockerVolumesRequest_LabelsEntry {
  key: string;
  value: string;
}

/** 获取储存卷列表响应 */
export interface ListDockerVolumesResponse {
  /** 储存卷列表 */
  items: DockerVolumeInfo[];
  /** 总数 */
  total: number;
}

/** 获取储存卷详情请求 */
export interface GetDockerVolumeRequest {
  /** 储存卷名称 */
  name: string;
}

/** 获取储存卷详情响应 */
export interface GetDockerVolumeResponse {
  /** 储存卷详情 */
  info: DockerVolumeInfo | undefined;
}

/** 创建储存卷请求 */
export interface CreateDockerVolumeRequest {
  /** 创建参数 */
  options: DockerVolumeCreateOptions | undefined;
}

/** 创建储存卷响应 */
export interface CreateDockerVolumeResponse {
  /** 储存卷详情 */
  info: DockerVolumeInfo | undefined;
}

/** 更新储存卷请求 */
export interface UpdateDockerVolumeRequest {
  /** 储存卷名称 */
  name: string;
  /** 标签 */
  labels: { [key: string]: string };
  /** 驱动参数 */
  driverOpts: { [key: string]: string };
  /** 储存卷创建参数 */
  options:
    | DockerVolumeCreateOptions
    | undefined;
  /** 是否强制重建 */
  force: boolean;
}

export interface UpdateDockerVolumeRequest_LabelsEntry {
  key: string;
  value: string;
}

export interface UpdateDockerVolumeRequest_DriverOptsEntry {
  key: string;
  value: string;
}

/** 更新储存卷响应 */
export interface UpdateDockerVolumeResponse {
  /** 储存卷详情 */
  info:
    | DockerVolumeInfo
    | undefined;
  /** 重建任务 */
  task: DockerTaskInfo | undefined;
}

/** 重建储存卷请求 */
export interface RecreateDockerVolumeRequest {
  /** 储存卷名称 */
  name: string;
  /** 创建参数 */
  options:
    | DockerVolumeCreateOptions
    | undefined;
  /** 是否强制删除 */
  force: boolean;
}

/** 重建储存卷响应 */
export interface RecreateDockerVolumeResponse {
  /** 任务 */
  task: DockerTaskInfo | undefined;
}

/** 删除储存卷请求 */
export interface DeleteDockerVolumeRequest {
  /** 储存卷名称 */
  name: string;
  /** 是否强制删除 */
  force: boolean;
}

/** 删除储存卷响应 */
export interface DeleteDockerVolumeResponse {
}

/** 清理储存卷请求 */
export interface PruneDockerVolumesRequest {
}

/** 清理储存卷响应 */
export interface PruneDockerVolumesResponse {
  /** 任务 */
  task: DockerTaskInfo | undefined;
}

/** 导出储存卷请求 */
export interface ExportDockerVolumeRequest {
  /** 储存卷名称 */
  name: string;
  /** 导出路径 */
  archivePath: string;
}

/** 导出储存卷响应 */
export interface ExportDockerVolumeResponse {
  /** 任务 */
  task: DockerTaskInfo | undefined;
}

/** 恢复储存卷请求 */
export interface RestoreDockerVolumeRequest {
  /** 储存卷名称 */
  name: string;
  /** 归档路径 */
  archivePath: string;
}

/** 恢复储存卷响应 */
export interface RestoreDockerVolumeResponse {
  /** 任务 */
  task: DockerTaskInfo | undefined;
}

/** 储存卷创建参数 */
export interface DockerVolumeCreateOptions {
  /** 储存卷名称 */
  name: string;
  /** 驱动 */
  driver: string;
  /** 标签 */
  labels: { [key: string]: string };
  /** 驱动参数 */
  driverOpts: { [key: string]: string };
}

export interface DockerVolumeCreateOptions_LabelsEntry {
  key: string;
  value: string;
}

export interface DockerVolumeCreateOptions_DriverOptsEntry {
  key: string;
  value: string;
}

/** 储存卷详情 */
export interface DockerVolumeInfo {
  /** 储存卷名称 */
  name: string;
  /** 驱动 */
  driver: string;
  /** 挂载点 */
  mountpoint: string;
  /** 创建时间 */
  createdAt: string;
  /** 状态 */
  status: { [key: string]: string };
  /** 标签 */
  labels: { [key: string]: string };
  /** 作用域 */
  scope: string;
  /** 驱动参数 */
  options: { [key: string]: string };
  /** 占用大小 */
  usageSize: number;
  /** 引用数量 */
  refCount: number;
}

export interface DockerVolumeInfo_StatusEntry {
  key: string;
  value: string;
}

export interface DockerVolumeInfo_LabelsEntry {
  key: string;
  value: string;
}

export interface DockerVolumeInfo_OptionsEntry {
  key: string;
  value: string;
}
