// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.0
// source: v1/file.proto

/* eslint-disable */

export const protobufPackage = "v1";

/** 文件排序字段 */
export enum FileSortField {
  /** FILE_SORT_FIELD_UNSPECIFIED - 未指定 */
  FILE_SORT_FIELD_UNSPECIFIED = "FILE_SORT_FIELD_UNSPECIFIED",
  /** FILE_SORT_FIELD_NAME - 名称 */
  FILE_SORT_FIELD_NAME = "FILE_SORT_FIELD_NAME",
  /** FILE_SORT_FIELD_UPDATE_TIME - 修改时间 */
  FILE_SORT_FIELD_UPDATE_TIME = "FILE_SORT_FIELD_UPDATE_TIME",
  UNRECOGNIZED = "UNRECOGNIZED",
}

/** 文件任务状态 */
export enum FileTaskStatus {
  /** FILE_TASK_STATUS_UNSPECIFIED - 未指定 */
  FILE_TASK_STATUS_UNSPECIFIED = "FILE_TASK_STATUS_UNSPECIFIED",
  /** FILE_TASK_STATUS_PENDING - 等待执行 */
  FILE_TASK_STATUS_PENDING = "FILE_TASK_STATUS_PENDING",
  /** FILE_TASK_STATUS_RUNNING - 执行中 */
  FILE_TASK_STATUS_RUNNING = "FILE_TASK_STATUS_RUNNING",
  /** FILE_TASK_STATUS_SUCCESS - 已完成 */
  FILE_TASK_STATUS_SUCCESS = "FILE_TASK_STATUS_SUCCESS",
  /** FILE_TASK_STATUS_FAILED - 执行失败 */
  FILE_TASK_STATUS_FAILED = "FILE_TASK_STATUS_FAILED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

/** 分享信息（仅创建者可见的管理视图，含提取码） */
export interface ShareInfo {
  /** 分享 id */
  id: string;
  /** 展示名称 */
  name: string;
  /** 被分享的真实路径 */
  targetPath: string;
  /** 是否文件夹 */
  isDir: boolean;
  /** 公开访问令牌 */
  token: string;
  /** 提取码，空=无需 */
  code: string;
  /** 过期时间，空=永久 */
  expiresAt:
    | Date
    | undefined;
  /** 下载次数上限，0=不限 */
  maxDownloads: number;
  /** 已下载次数 */
  downloadCount: number;
  /** 是否启用 */
  enabled: boolean;
  /** 创建时间 */
  createTime:
    | Date
    | undefined;
  /** 更新时间 */
  updateTime:
    | Date
    | undefined;
  /** 文件来源id，空=本地磁盘 */
  sourceId: string;
}

/** 创建分享请求 */
export interface CreateShareRequest {
  /** 要分享的文件/文件夹路径 */
  path: string;
  /** 展示名称，空=路径名 */
  name: string;
  /** 提取码，空=公开 */
  code: string;
  /** 过期时间，空=永久 */
  expiresAt:
    | Date
    | undefined;
  /** 下载次数上限，0=不限 */
  maxDownloads: number;
  /** 是否启用 */
  enabled: boolean;
  /** 文件来源id，空=本地磁盘 */
  sourceId: string;
  /** 文件大小（前端提供的展示值，可自定义，单文件分享的公开元信息展示用） */
  size: number;
}

/** 创建分享响应 */
export interface CreateShareResponse {
  /** 分享信息 */
  info: ShareInfo | undefined;
}

/** 分享列表请求 */
export interface ListSharesRequest {
  /** 页码 */
  page: number;
  /** 每页数量 */
  pageSize: number;
  /** 搜索关键字（名称/路径） */
  keywords?: string | undefined;
}

/** 分享列表响应 */
export interface ListSharesResponse {
  /** 列表 */
  items: ShareInfo[];
  /** 当前页码 */
  page: number;
  /** 每页数量 */
  pageSize: number;
  /** 总数 */
  total: number;
}

/** 更新分享请求（全量覆盖可编辑字段） */
export interface UpdateShareRequest {
  /** 分享 id */
  id: string;
  /** 展示名称 */
  name: string;
  /** 提取码，空=公开 */
  code: string;
  /** 过期时间，空=永久 */
  expiresAt:
    | Date
    | undefined;
  /** 下载次数上限，0=不限 */
  maxDownloads: number;
  /** 是否启用 */
  enabled: boolean;
  /** 新的分享目标路径（文件/文件夹），空=不修改；修改不影响原有分享链接（token 不变） */
  path: string;
  /** 新目标的文件来源id（path 非空时生效） */
  sourceId: string;
  /** 新目标文件大小（前端提供的展示值，path 非空时生效） */
  size: number;
}

/** 更新分享响应 */
export interface UpdateShareResponse {
  /** 分享信息 */
  info: ShareInfo | undefined;
}

/** 删除分享请求 */
export interface DeleteShareRequest {
  /** 分享 id */
  id: string;
}

/** 删除分享响应 */
export interface DeleteShareResponse {
}

/** 获取分享元信息请求（公开） */
export interface GetShareMetaRequest {
  /** 公开访问令牌 */
  token: string;
}

/** 获取分享元信息响应（公开，不含提取码本身） */
export interface GetShareMetaResponse {
  /** 展示名称 */
  name: string;
  /** 是否文件夹 */
  isDir: boolean;
  /** 文件大小（文件夹为 0） */
  size: number;
  /** 是否需要提取码 */
  needCode: boolean;
  /** 过期时间，空=永久 */
  expiresAt:
    | Date
    | undefined;
  /** 下载次数上限，0=不限 */
  maxDownloads: number;
  /** 已下载次数 */
  downloadCount: number;
  /** 当前是否可用（启用/未过期/未超次数） */
  available: boolean;
  /** 分享者昵称（公开展示） */
  ownerName: string;
  /** 分享者头像（公开展示） */
  ownerAvatar: string;
}

/** 浏览分享目录请求（公开，需会话签名） */
export interface ListShareDirRequest {
  /** 公开访问令牌 */
  token: string;
  /** 会话签名（由 CreateShareSession 换取，替代逐次携带提取码） */
  sign: string;
  /** 分享根下的相对子路径，空=根 */
  subPath: string;
}

/** 分享目录条目 */
export interface ShareEntry {
  /** 名称 */
  name: string;
  /** 是否目录 */
  isDir: boolean;
  /** 大小 */
  size: number;
  /** 修改时间 */
  updateTime:
    | Date
    | undefined;
  /** 相对分享根的路径（用于继续浏览/下载） */
  relPath: string;
}

/** 浏览分享目录响应 */
export interface ListShareDirResponse {
  /** 条目列表 */
  items: ShareEntry[];
  /** 当前子路径 */
  subPath: string;
}

/** 换取分享会话签名请求（公开） */
export interface CreateShareSessionRequest {
  /** 公开访问令牌 */
  token: string;
  /** 提取码（如分享设置了） */
  code: string;
}

/** 换取分享会话签名响应（公开） */
export interface CreateShareSessionResponse {
  /** 会话签名；为空表示需要先通过验证（见 need_code/message） */
  sign: string;
  /** 签名过期时间（限时分享下不晚于分享过期时间） */
  expiresAt:
    | Date
    | undefined;
  /** 是否需要提取码（未提供或错误） */
  needCode: boolean;
  /** 失败原因（已关闭/已过期/次数用尽/提取码错误等） */
  message: string;
}

/** 文件来源能力（供前端隐藏/禁用不支持的动作） */
export interface FileSourceCaps {
  /** 支持预签名直链（启用 302 跳转的前提） */
  presign: boolean;
  /** 支持复制 */
  copy: boolean;
  /** 支持移动/剪切 */
  move: boolean;
  /** 支持压缩/解压 */
  compress: boolean;
  /** 支持断点续传上传 */
  resumableUpload: boolean;
}

/** 文件来源类型相关配置（密钥字段仅写入、响应中恒为空） */
export interface FileSourceConfig {
  /**
   * —— OSS / S3 ——
   * 访问端点，如 oss-cn-hangzhou.aliyuncs.com / s3.amazonaws.com / minio:9000
   */
  endpoint: string;
  /** 区域 */
  region: string;
  /** 桶名 */
  bucket: string;
  /** Access Key ID */
  accessKey: string;
  /** Secret Key（仅写入，响应恒为空；更新时留空=保留原值） */
  secretKey: string;
  /** 基础路径/对象 key 前缀 */
  prefix: string;
  /** 是否使用 https */
  useSsl: boolean;
  /** 是否 path-style（MinIO 等需要） */
  pathStyle: boolean;
  /**
   * —— FTP / WebDAV ——
   * 主机
   */
  host: string;
  /** 端口 */
  port: number;
  /** 用户名 */
  username: string;
  /** 密码（仅写入，响应恒为空；更新时留空=保留原值） */
  password: string;
  /** 基础路径 */
  basePath: string;
  /** 是否启用 TLS（FTP over TLS） */
  tls: boolean;
  /**
   * —— WebDAV ——
   * 完整 WebDAV 基础 URL，如 https://dav.example.com/remote.php/dav/files/me
   */
  url: string;
}

/** 文件来源信息 */
export interface FileSourceInfo {
  /** id */
  id: string;
  /** 展示名称 */
  name: string;
  /** 类型 oss/ftp/webdav */
  type: string;
  /** 是否启用 */
  enabled: boolean;
  /** 是否优先 302 直链 */
  redirect302: boolean;
  /** 配置（密钥字段为空） */
  config:
    | FileSourceConfig
    | undefined;
  /** 能力 */
  caps:
    | FileSourceCaps
    | undefined;
  /** 创建者昵称 */
  creatorName: string;
  /** 创建时间 */
  createTime:
    | Date
    | undefined;
  /** 更新时间 */
  updateTime: Date | undefined;
}

/** 文件来源列表请求 */
export interface ListFileSourcesRequest {
  /** 搜索关键字（名称） */
  keywords?:
    | string
    | undefined;
  /** 只返回已启用（文件浏览器下拉用） */
  enabledOnly?: boolean | undefined;
}

/** 文件来源列表响应 */
export interface ListFileSourcesResponse {
  /** 列表 */
  items: FileSourceInfo[];
}

/** 新增文件来源请求 */
export interface CreateFileSourceRequest {
  /** 展示名称 */
  name: string;
  /** 类型 oss/ftp/webdav */
  type: string;
  /** 是否启用 */
  enabled: boolean;
  /** 是否优先 302 直链 */
  redirect302: boolean;
  /** 配置 */
  config: FileSourceConfig | undefined;
}

/** 新增文件来源响应 */
export interface CreateFileSourceResponse {
  /** 来源信息 */
  info: FileSourceInfo | undefined;
}

/** 更新文件来源请求 */
export interface UpdateFileSourceRequest {
  /** id */
  id: string;
  /** 展示名称 */
  name: string;
  /** 是否启用 */
  enabled: boolean;
  /** 是否优先 302 直链 */
  redirect302: boolean;
  /** 配置（密钥字段留空=保留原值） */
  config: FileSourceConfig | undefined;
}

/** 更新文件来源响应 */
export interface UpdateFileSourceResponse {
  /** 来源信息 */
  info: FileSourceInfo | undefined;
}

/** 删除文件来源请求 */
export interface DeleteFileSourceRequest {
  /** id */
  id: string;
}

/** 删除文件来源响应 */
export interface DeleteFileSourceResponse {
}

/** 测试文件来源连通性请求（传 id 测已存在来源；或传 type+config 测未保存配置） */
export interface TestFileSourceRequest {
  /** 已存在来源 id（优先） */
  id: string;
  /** 类型 oss/ftp/webdav */
  type: string;
  /** 配置 */
  config: FileSourceConfig | undefined;
}

/** 测试文件来源连通性响应 */
export interface TestFileSourceResponse {
  /** 是否连通 */
  ok: boolean;
  /** 结果消息 */
  message: string;
}

/** 获取系统文件列表请求 */
export interface GetFileSystemListRequest {
  /** 目录路径 */
  path: string;
  /** 页码 */
  page: number;
  /** 每页数量 */
  pageSize: number;
  /** 搜索关键字 */
  keywords?:
    | string
    | undefined;
  /** 是否包含子目录-搜索关键字 */
  includeSubDir?:
    | boolean
    | undefined;
  /** 排序字段 */
  sortField: FileSortField;
  /** 排序是否倒序 */
  isDesc: boolean;
  /** 文件来源id，空=本地磁盘 */
  sourceId: string;
}

/** 获取系统文件列表响应 */
export interface GetFileSystemListResponse {
  /** 当前目录信息 */
  directory:
    | FileDirectoryInfo
    | undefined;
  /** 文件列表 */
  items: FileEntryInfo[];
  /** 当前页码 */
  page: number;
  /** 每页数量 */
  pageSize: number;
  /** 总数 */
  total: number;
}

/** 目录信息 */
export interface FileDirectoryInfo {
  /** 目录名称 */
  name: string;
  /** 目录路径 */
  path: string;
  /** 父级目录路径 */
  parentPath: string;
  /** 子目录数量 */
  dirCount: number;
  /** 文件数量 */
  fileCount: number;
  /** 条目总数 */
  itemCount: number;
}

/** 系统文件条目信息 */
export interface FileEntryInfo {
  /** 名称 */
  name: string;
  /** 完整路径 */
  path: string;
  /** 是否目录 */
  isDir: boolean;
  /** 权限 */
  permission: string;
  /** 用户名 */
  userName: string;
  /** 用户id */
  userId: number;
  /** 用户组名 */
  groupName: string;
  /** 用户组id */
  groupId: number;
  /** 文件大小 */
  size: number;
  /** 修改时间 */
  updateTime: Date | undefined;
}

/** 目录树节点(懒加载，仅含直接子项的轻量信息；instance.proto 已 import 本文件可复用) */
export interface FileTreeNode {
  /** 名称 */
  name: string;
  /** 完整路径(回传以继续展开/打开) */
  path: string;
  /** 是否目录 */
  isDir: boolean;
}

/** 获取目录树请求(系统级) */
export interface GetFileSystemTreeRequest {
  /** 目录路径，空=根目录 */
  path: string;
  /** 文件来源id，空=本地磁盘 */
  sourceId: string;
}

/** 获取目录树响应(系统级) */
export interface GetFileSystemTreeResponse {
  /** 实际列出的目录路径(回显) */
  path: string;
  /** 直接子项(目录在前，按名称排序) */
  nodes: FileTreeNode[];
}

/** 批量计算系统文件夹大小响应 */
export interface BatchCalcFileSystemSizeResponse {
  /** 计算结果列表 */
  items: FileSizeResult[];
}

/** 系统文件大小结果 */
export interface FileSizeResult {
  /** 路径 */
  path: string;
  /** 大小 */
  size: number;
  /** 是否成功 */
  success: boolean;
  /** 结果消息 */
  message: string;
}

/** 批量删除系统文件请求 */
export interface BatchDeleteFileSystemRequest {
  /** 路径列表 */
  paths: string[];
  /** 文件来源id，空=本地磁盘 */
  sourceId: string;
}

/** 批量删除系统文件响应 */
export interface BatchDeleteFileSystemResponse {
  /** 删除结果列表 */
  items: FileOperationResult[];
}

/** 批量创建系统文件请求 */
export interface CreateFileSystemRequest {
  /** 创建信息 */
  info:
    | FileCreateItem
    | undefined;
  /** 文件来源id，空=本地磁盘 */
  sourceId: string;
}

/** 批量创建系统文件响应 */
export interface CreateFileSystemResponse {
}

/** 重命名系统文件请求 */
export interface RenameFileSystemRequest {
  /** 原路径 */
  path: string;
  /** 新名称，不包含路径 */
  newName: string;
  /** 文件来源id，空=本地磁盘 */
  sourceId: string;
}

/** 重命名系统文件响应 */
export interface RenameFileSystemResponse {
  /** 重命名后的路径 */
  path: string;
}

/** 复制系统文件请求 */
export interface CopyFileSystemRequest {
  /** 路径列表 */
  paths: string[];
  /** 目标目录路径 */
  targetPath: string;
  /** 文件来源id，空=本地磁盘 */
  sourceId: string;
}

/** 复制系统文件响应 */
export interface CopyFileSystemResponse {
  /** 异步任务信息 */
  task: FileTaskInfo | undefined;
}

/** 剪贴系统文件请求 */
export interface CutFileSystemRequest {
  /** 路径列表 */
  paths: string[];
  /** 目标目录路径 */
  targetPath: string;
  /** 文件来源id，空=本地磁盘 */
  sourceId: string;
}

/** 剪贴系统文件响应 */
export interface CutFileSystemResponse {
  /** 异步任务信息 */
  task: FileTaskInfo | undefined;
}

/** 获取文件任务请求 */
export interface GetFileTaskRequest {
  /** 任务id */
  taskId: string;
}

/** 获取文件任务响应 */
export interface GetFileTaskResponse {
  /** 任务信息 */
  task: FileTaskInfo | undefined;
}

/** 文件异步任务信息 */
export interface FileTaskInfo {
  /** 任务id */
  taskId: string;
  /** 操作类型 */
  operation: string;
  /** 任务状态 */
  status: FileTaskStatus;
  /** 总任务数 */
  total: number;
  /** 已完成任务数 */
  finished: number;
  /** 消息 */
  message: string;
  /** 文件操作结果 */
  items: FileOperationResult[];
  /** 创建时间 */
  createTime:
    | Date
    | undefined;
  /** 更新时间 */
  updateTime: Date | undefined;
}

/** 批量压缩系统文件请求 */
export interface BatchCompressFileSystemRequest {
  /** 路径列表 */
  paths: string[];
  /** 目标压缩文件路径，不传时由服务端自动生成 */
  targetPath?:
    | string
    | undefined;
  /** 文件来源id，空=本地磁盘 */
  sourceId: string;
}

/** 批量压缩系统文件响应 */
export interface BatchCompressFileSystemResponse {
  /** 实际生成的压缩文件路径 */
  outputPath: string;
}

/** 解压系统文件请求 */
export interface UnzipFileSystemRequest {
  /** 压缩文件路径 */
  path: string;
  /** 解压目标目录，不传时由服务端自动生成 */
  targetPath?:
    | string
    | undefined;
  /** 文件来源id，空=本地磁盘 */
  sourceId: string;
}

/** 解压系统文件响应 */
export interface UnzipFileSystemResponse {
  /** 实际生成的解压目录路径 */
  outputPath: string;
}

/** 系统文件创建项 */
export interface FileCreateItem {
  /** 路径 */
  path: string;
  /** 是否目录 */
  isDir: boolean;
  /** 文件内容，目录时忽略 */
  content: Uint8Array;
}

/** 系统文件操作结果 */
export interface FileOperationResult {
  /** 路径 */
  path: string;
  /** 是否成功 */
  success: boolean;
  /** 结果消息 */
  message: string;
}

/** 编辑系统文件请求 */
export interface EditFileSystemFileRequest {
  /** 文件路径 */
  path: string;
  /** 文件内容 */
  content: Uint8Array;
  /** 文件来源id，空=本地磁盘 */
  sourceId: string;
}

/** 编辑系统文件响应 */
export interface EditFileSystemFileResponse {
}

/** 文件下载预签名请求 */
export interface FileSystemPreSignRequest {
  /** 路径 */
  path: string;
  /** 文件来源id，空=本地磁盘 */
  sourceId: string;
  /** 是否内联预览（true=inline 预览，false=attachment 下载） */
  inline: boolean;
}

/** 文件下载预签名响应 */
export interface FileSystemPreSignResponse {
  /** 下载路径 */
  downloadUrlPath: string;
}

/** 文件上传预签名(系统级)请求 */
export interface FileSystemPreSignUploadRequest {
  /** 文件路径 */
  path: string;
  /** 文件名称 */
  fileName: string;
  /** 文件总大小（字节） */
  fileSize: number;
  /** 快速hash */
  hash: string;
  /** 分片大小（字节），不传时由服务端自动决定 */
  partSize?:
    | number
    | undefined;
  /** 文件来源id，空=本地磁盘 */
  sourceId: string;
}

/** 文件上传预签名(系统级)响应 */
export interface FileSystemPreSignUploadResponse {
  /** 信息 */
  info: UploadInfo | undefined;
}

/** 获取上传状态请求 */
export interface GetFileUploadStatusRequest {
  /** 上传id */
  uploadId: string;
}

/** 获取上传状态响应 */
export interface GetFileUploadStatusResponse {
  /** 信息 */
  info: UploadInfo | undefined;
}

/** 上传完成合并分片请求 */
export interface CompleteFileUploadRequest {
  /** 上传id */
  uploadId: string;
}

/** 上传完成合并分片响应 */
export interface CompleteFileUploadResponse {
  /** 远端长收尾（FTP/WebDAV）异步任务；本地/OSS 瞬时收尾时为空。前端据此决定是否轮询任务。 */
  task: FileTaskInfo | undefined;
}

/** 取消文件上传请求 */
export interface CancelFileUploadRequest {
  /** 上传id */
  uploadId: string;
}

/** 取消文件上传响应 */
export interface CancelFileUploadResponse {
}

/** 上传信息 */
export interface UploadInfo {
  /** 上传会话 id */
  uploadId: string;
  /** 实际分片大小（字节） */
  partSize: number;
  /** 文件总大小（字节） */
  fileSize: number;
  /** 总分片数 */
  totalParts: number;
  /** 已上传完成的分片序号 <切片,hash> */
  uploadedParts: { [key: number]: string };
  /** 是否已完成上传 */
  completed: boolean;
  /** 是否已取消上传 */
  cancel: boolean;
  /** 预签名过期时间 */
  expiredAt:
    | Date
    | undefined;
  /**
   * 各分片的上传 URL（partNumber→URL）。本地/FTP/WebDAV 指向 momoko 签名端点，OSS 指向来源预签名直链。
   * 前端对每片 PUT part_urls[n]，来源透明、一套代码。
   */
  partUrls: { [key: number]: string };
}

export interface UploadInfo_UploadedPartsEntry {
  key: number;
  value: string;
}

export interface UploadInfo_PartUrlsEntry {
  key: number;
  value: string;
}
