// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.0
// source: v1/initialize.proto

/* eslint-disable */

export const protobufPackage = "v1";

/** 数据库类型 */
export enum DatabaseType {
  /** DatabaseType_Unspecified - 未指定 */
  DatabaseType_Unspecified = "DatabaseType_Unspecified",
  /** DatabaseType_SQLite - SQLite */
  DatabaseType_SQLite = "DatabaseType_SQLite",
  /** DatabaseType_MySQL - MySQL */
  DatabaseType_MySQL = "DatabaseType_MySQL",
  /** DatabaseType_PostgreSQL - PostgreSQL */
  DatabaseType_PostgreSQL = "DatabaseType_PostgreSQL",
  UNRECOGNIZED = "UNRECOGNIZED",
}

/** 初始化数据库配置 */
export interface InitializeDatabaseConfig {
  /** 数据库类型 */
  type: DatabaseType;
  /** SQLite 数据库文件路径 */
  sqlitePath: string;
  /** MySQL/PostgreSQL 连接地址，格式为 host 或 host:port */
  address: string;
  /** MySQL/PostgreSQL 用户名 */
  username: string;
  /** MySQL/PostgreSQL 密码 */
  password: string;
  /** MySQL/PostgreSQL 数据库名 */
  databaseName: string;
}

/** 初始化超级管理员 */
export interface InitializeAdminUser {
  /** 用户名 */
  username: string;
  /** 密码 */
  password: string;
  /** 邮箱 */
  email: string;
  /** 昵称 */
  name: string;
}

/** 获取系统初始化状态请求 */
export interface InitializeStatusRequest {
}

/** 获取系统初始化状态响应 */
export interface InitializeStatusResponse {
  /** 是否已初始化 */
  initialized: boolean;
  /** 支持的数据库类型 */
  supportedDatabaseTypes: DatabaseType[];
}

/** 确认系统初始化请求 */
export interface ConfirmInitializeRequest {
  /** 数据库配置 */
  database:
    | InitializeDatabaseConfig
    | undefined;
  /** 超级管理员 */
  admin: InitializeAdminUser | undefined;
}

/** 确认系统初始化响应 */
export interface ConfirmInitializeResponse {
  /** 是否已初始化 */
  initialized: boolean;
  /** 是否需要重启服务 */
  restartRequired: boolean;
}

/** 测试数据库连接请求 */
export interface TestInitializeDatabaseRequest {
  /** 数据库配置 */
  database: InitializeDatabaseConfig | undefined;
}

/** 测试数据库连接响应 */
export interface TestInitializeDatabaseResponse {
  /** 是否连接成功 */
  success: boolean;
}
