// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.0
// source: v1/instance.proto

/* eslint-disable */
import type {
  FileCreateItem,
  FileDirectoryInfo,
  FileEntryInfo,
  FileOperationResult,
  FileSortField,
  FileTaskInfo,
  FileTreeNode,
  UploadInfo,
} from "./file";

export const protobufPackage = "v1";

/** 实例状态 */
export enum InstanceStatus {
  /** INSTANCE_STATUS_UNSPECIFIED - 未指定 */
  INSTANCE_STATUS_UNSPECIFIED = "INSTANCE_STATUS_UNSPECIFIED",
  /** INSTANCE_STATUS_STOPPED - 停止 */
  INSTANCE_STATUS_STOPPED = "INSTANCE_STATUS_STOPPED",
  /** INSTANCE_STATUS_RUNNING - 运行中 */
  INSTANCE_STATUS_RUNNING = "INSTANCE_STATUS_RUNNING",
  /** INSTANCE_STATUS_MAINTENANCE - 维护 */
  INSTANCE_STATUS_MAINTENANCE = "INSTANCE_STATUS_MAINTENANCE",
  UNRECOGNIZED = "UNRECOGNIZED",
}

/** 获取实例类型请求 */
export interface GetInstanceTypesRequest {
}

/** 获取实例类型响应 */
export interface GetInstanceTypesResponse {
  /** 类型列表 */
  types: InstanceTypeInfo[];
}

/** 创建实例类型请求 */
export interface CreateInstanceTypeRequest {
  /** 类型名称 */
  name: string;
}

/** 创建实例类型响应 */
export interface CreateInstanceTypeResponse {
  /** 实例信息 */
  type: InstanceTypeInfo | undefined;
}

/** 更新实例类型请求 */
export interface UpdateInstanceTypeRequest {
  /** 类型id */
  id: string;
  /** 类型名称 */
  name?:
    | string
    | undefined;
  /** 是否启用 */
  isEnable?: boolean | undefined;
}

/** 更新实例类型响应 */
export interface UpdateInstanceTypeResponse {
  /** 实例信息 */
  type: InstanceTypeInfo | undefined;
}

/** 删除实例类型请求 */
export interface DelInstanceTypeRequest {
  /** 类型id */
  id: string;
}

/** 删除实例类型响应 */
export interface DelInstanceTypeResponse {
}

/** 实例类型信息 */
export interface InstanceTypeInfo {
  /** 类型id */
  id: string;
  /** 类型名称 */
  name: string;
  /** 是否系统内置 */
  isSystem: boolean;
  /** 是否启用 */
  isEnable: boolean;
}

/** 获取实例列表请求 */
export interface GetInstancesRequest {
  /** page */
  page: number;
  /** page size */
  pageSize: number;
  /** 实例名称/标签 */
  keywords?:
    | string
    | undefined;
  /** 类型 */
  type?:
    | string
    | undefined;
  /** 状态 */
  status?: InstanceStatus | undefined;
}

/** 获取实例列表响应 */
export interface GetInstancesResponse {
  /** actual page */
  page: number;
  /** actual page size */
  pageSize: number;
  /** 总数 */
  total: number;
  /** 列表 */
  infos: InstanceInfo[];
}

/** 创建实例请求 */
export interface CreateInstanceRequest {
  /** 实例名称 */
  name: string;
  /** 备注 */
  remark: string;
  /** 标签(,号隔开) */
  tags: string;
  /** 类型 */
  type: string;
  /** 所属用户id */
  userId: string;
  /** 启动命令 */
  startCommand: string;
  /** 实例路径 */
  instancePath: string;
  /** 停止命令 */
  stopCommand: string;
  /** 是否自启动 */
  autoStart: boolean;
  /** 环境变量(一行一个 如:GO_WANT_HELPER_PROCESS=1 */
  env: string[];
}

/** 创建实例响应 */
export interface CreateInstanceResponse {
  /** 实例详情 */
  info: InstanceInfo | undefined;
}

/** 获取实例详情请求 */
export interface GetInstanceInfoRequest {
  /** id */
  id: string;
}

/** 获取实例详情响应 */
export interface GetInstanceInfoResponse {
  /** 实例详情 */
  info: InstanceInfo | undefined;
}

/** 获取实例控制台详情请求 */
export interface GetInstanceTerminalInfoRequest {
  /** 实例id */
  id: string;
}

/** 获取实例控制台详情响应 */
export interface GetInstanceTerminalInfoResponse {
}

/** 启动实例请求 */
export interface StartInstanceRequest {
  /** 实例id */
  id: string;
}

/** 启动实例响应 */
export interface StartInstanceResponse {
  /** 实例详情 */
  info: InstanceInfo | undefined;
}

/** 停止实例请求 */
export interface StopInstanceRequest {
  /** 实例id */
  id: string;
  /** 是否强制停止 */
  force: boolean;
}

/** 停止实例响应 */
export interface StopInstanceResponse {
}

/** 重启实例请求 */
export interface RestartInstanceRequest {
  /** 实例id */
  id: string;
  /** 是否强制重启 */
  force: boolean;
}

/** 重启实例响应 */
export interface RestartInstanceResponse {
}

/** 删除实例请求 */
export interface DelInstanceRequest {
  /** 实例id */
  id: string;
}

/** 删除实例响应 */
export interface DelInstanceResponse {
}

export interface UpdateInstanceRequest {
  /** 实例id */
  id: string;
  /** 实例名称 */
  name?:
    | string
    | undefined;
  /** 备注 */
  remark?:
    | string
    | undefined;
  /** 标签(,号隔开) */
  tags?:
    | string
    | undefined;
  /** 类型 */
  type?:
    | string
    | undefined;
  /** 启动命令 */
  startCommand?:
    | string
    | undefined;
  /** 实例路径 */
  instancePath?:
    | string
    | undefined;
  /** 停止命令 */
  stopCommand?:
    | string
    | undefined;
  /** 是否自启动 */
  autoStart?:
    | boolean
    | undefined;
  /** 环境变量(一行一个 如:GO_WANT_HELPER_PROCESS=1 */
  env: string[];
}

export interface UpdateInstanceResponse {
  /** 实例详情 */
  info: InstanceInfo | undefined;
}

/** 删除实例日志请求 */
export interface DelInstanceLogRequest {
  /** 实例id */
  id: string;
}

/** 删除实例日志响应 */
export interface DelInstanceLogResponse {
}

/** 实例详情 */
export interface InstanceInfo {
  /** 实例id */
  id: string;
  /** 实例名称 */
  name: string;
  /** 实例状态 */
  status: InstanceStatus;
  /** 启动时间 */
  startTime:
    | Date
    | undefined;
  /** 创建时间 */
  createTime:
    | Date
    | undefined;
  /** 备注 */
  remark: string;
  /** 标签(,号隔开) */
  tags: string;
  /** 类型 */
  type: string;
  /** 所属用户id */
  userId: string;
  /** 启动命令 */
  startCommand: string;
  /** 实例路径 */
  instancePath: string;
  /** ws路径(启动时才有 */
  wsPath: string;
  /** 停止命令 */
  stopCommand: string;
  /** 是否自启动 */
  autoStart: boolean;
  /** 环境变量(一行一个 如:GO_WANT_HELPER_PROCESS=1 */
  env: string[];
}

/** 获取实例文件列表请求 */
export interface GetInstanceFileListRequest {
  /** 实例id */
  id: string;
  /** 实例目录内相对路径；空值表示实例根目录 */
  path: string;
  /** 页码 */
  page: number;
  /** 每页数量 */
  pageSize: number;
  /** 搜索关键字 */
  keywords?:
    | string
    | undefined;
  /** 搜索时是否包含子目录 */
  includeSubDir?:
    | boolean
    | undefined;
  /** 排序字段 */
  sortField: FileSortField;
  /** 排序是否倒序 */
  isDesc: boolean;
}

/** 获取实例文件列表响应 */
export interface GetInstanceFileListResponse {
  /** 当前目录信息 */
  directory:
    | FileDirectoryInfo
    | undefined;
  /** 文件列表 */
  items: FileEntryInfo[];
  /** 当前页码 */
  page: number;
  /** 每页数量 */
  pageSize: number;
  /** 总数 */
  total: number;
}

/** 获取实例目录树请求(复用 file.proto 的 FileTreeNode) */
export interface GetInstanceFileTreeRequest {
  /** 实例id */
  id: string;
  /** 实例目录内相对路径；空值表示实例根目录 */
  path: string;
}

/** 获取实例目录树响应 */
export interface GetInstanceFileTreeResponse {
  /** 实际列出的目录路径(回显) */
  path: string;
  /** 直接子项(目录在前，按名称排序) */
  nodes: FileTreeNode[];
}

/** 创建实例文件请求 */
export interface CreateInstanceFileRequest {
  /** 实例id */
  id: string;
  /** 创建信息；path 为实例目录内相对路径 */
  info: FileCreateItem | undefined;
}

/** 创建实例文件响应 */
export interface CreateInstanceFileResponse {
}

/** 重命名实例文件请求 */
export interface RenameInstanceFileRequest {
  /** 实例id */
  id: string;
  /** 原路径 */
  path: string;
  /** 新名称，不包含路径 */
  newName: string;
}

/** 重命名实例文件响应 */
export interface RenameInstanceFileResponse {
  /** 重命名后的路径 */
  path: string;
}

/** 复制实例文件请求 */
export interface CopyInstanceFileRequest {
  /** 实例id */
  id: string;
  /** 实例目录内相对路径列表 */
  paths: string[];
  /** 目标目录相对路径 */
  targetPath: string;
}

/** 复制实例文件响应 */
export interface CopyInstanceFileResponse {
  /** 异步任务信息 */
  task: FileTaskInfo | undefined;
}

/** 剪贴实例文件请求 */
export interface CutInstanceFileRequest {
  /** 实例id */
  id: string;
  /** 实例目录内相对路径列表 */
  paths: string[];
  /** 目标目录相对路径 */
  targetPath: string;
}

/** 剪贴实例文件响应 */
export interface CutInstanceFileResponse {
  /** 异步任务信息 */
  task: FileTaskInfo | undefined;
}

/** 批量删除实例文件请求 */
export interface BatchDeleteInstanceFileRequest {
  /** 实例id */
  id: string;
  /** 实例目录内相对路径列表 */
  paths: string[];
}

/** 批量删除实例文件响应 */
export interface BatchDeleteInstanceFileResponse {
  /** 删除结果列表 */
  items: FileOperationResult[];
}

/** 压缩实例文件请求 */
export interface BatchCompressInstanceFileRequest {
  /** 实例id */
  id: string;
  /** 实例目录内相对路径列表 */
  paths: string[];
  /** 目标压缩文件相对路径，不传时由服务端自动生成 */
  targetPath?: string | undefined;
}

/** 压缩实例文件响应 */
export interface BatchCompressInstanceFileResponse {
  /** 实际生成的相对路径 */
  outputPath: string;
}

/** 解压实例文件请求 */
export interface UnzipInstanceFileRequest {
  /** 实例id */
  id: string;
  /** 压缩文件相对路径 */
  path: string;
  /** 解压目标目录相对路径，不传时由服务端自动生成 */
  targetPath?: string | undefined;
}

/** 解压实例文件响应 */
export interface UnzipInstanceFileResponse {
  /** 实际生成的相对路径 */
  outputPath: string;
}

/** 编辑实例文件请求 */
export interface EditInstanceFileRequest {
  /** 实例id */
  id: string;
  /** 文件相对路径 */
  path: string;
  /** 文件内容 */
  content: Uint8Array;
}

/** 编辑实例文件响应 */
export interface EditInstanceFileResponse {
}

/** 实例文件下载预签名请求 */
export interface InstanceFilePreSignRequest {
  /** 实例id */
  id: string;
  /** 文件相对路径 */
  path: string;
}

/** 实例文件下载预签名响应 */
export interface InstanceFilePreSignResponse {
  /** 下载路径 */
  downloadUrlPath: string;
}

/** 实例文件上传预签名请求 */
export interface InstanceFilePreSignUploadRequest {
  /** 实例id */
  id: string;
  /** 上传目录相对路径 */
  path: string;
  /** 文件名称 */
  fileName: string;
  /** 文件总大小（字节） */
  fileSize: number;
  /** 快速hash */
  hash: string;
  /** 分片大小（字节），不传时由服务端自动决定 */
  partSize?: number | undefined;
}

/** 实例文件上传预签名响应 */
export interface InstanceFilePreSignUploadResponse {
  /** 上传信息 */
  info: UploadInfo | undefined;
}
