// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.0
// source: v1/network.proto

/* eslint-disable */

export const protobufPackage = "v1";

export enum PortForwardType {
  /** PORT_FORWARD_TYPE_UNSPECIFIED - 未指定 */
  PORT_FORWARD_TYPE_UNSPECIFIED = "PORT_FORWARD_TYPE_UNSPECIFIED",
  /** PORT_FORWARD_TYPE_TCP - TCP */
  PORT_FORWARD_TYPE_TCP = "PORT_FORWARD_TYPE_TCP",
  /** PORT_FORWARD_TYPE_UDP - UDP */
  PORT_FORWARD_TYPE_UDP = "PORT_FORWARD_TYPE_UDP",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface ListPortForwardsRequest {
  /** page */
  page: number;
  /** page size */
  pageSize: number;
  /** 名称/地址 */
  keywords?:
    | string
    | undefined;
  /** 转发类型 */
  type?:
    | PortForwardType
    | undefined;
  /** 是否启用 */
  isEnable?: boolean | undefined;
}

export interface ListPortForwardsResponse {
  /** actual page */
  page: number;
  /** actual page size */
  pageSize: number;
  /** 总数 */
  total: number;
  /** 列表 */
  infos: PortForwardInfo[];
}

export interface CreatePortForwardRequest {
  /** 名称 */
  name: string;
  /** 转发类型 */
  type: PortForwardType;
  /** 监听地址 */
  listenAddress: string;
  /** 监听端口 */
  listenPort: number;
  /** 目标地址 */
  targetAddress: string;
  /** 目标端口 */
  targetPort: number;
  /** 是否启用 */
  isEnable: boolean;
}

export interface CreatePortForwardResponse {
  /** 端口转发详情 */
  info: PortForwardInfo | undefined;
}

export interface GetPortForwardRequest {
  /** 端口转发 id */
  id: string;
}

export interface GetPortForwardResponse {
  /** 端口转发详情 */
  info: PortForwardInfo | undefined;
}

export interface UpdatePortForwardRequest {
  /** 端口转发 id */
  id: string;
  /** 名称 */
  name?:
    | string
    | undefined;
  /** 转发类型 */
  type?:
    | PortForwardType
    | undefined;
  /** 监听地址 */
  listenAddress?:
    | string
    | undefined;
  /** 监听端口 */
  listenPort?:
    | number
    | undefined;
  /** 目标地址 */
  targetAddress?:
    | string
    | undefined;
  /** 目标端口 */
  targetPort?:
    | number
    | undefined;
  /** 是否启用 */
  isEnable?: boolean | undefined;
}

export interface UpdatePortForwardResponse {
  /** 端口转发详情 */
  info: PortForwardInfo | undefined;
}

export interface DeletePortForwardRequest {
  /** 端口转发 id */
  id: string;
}

export interface DeletePortForwardResponse {
}

export interface GetPortForwardStatsRequest {
  /** 端口转发 id */
  id: string;
  /** 起始时间(Unix 毫秒)，不传或<=0 时默认结束时间往前 1 小时 */
  startTimeMs: number;
  /** 结束时间(Unix 毫秒)，不传或<=0 时默认当前时间 */
  endTimeMs: number;
}

export interface GetPortForwardStatsResponse {
  /** 当前快照 */
  snapshot:
    | PortForwardStat
    | undefined;
  /** 时间序列样本（按时间升序，流量为累计值） */
  points: PortForwardStatPoint[];
  /** 采样间隔(秒) */
  sampleIntervalSeconds: number;
}

/** 端口转发实时快照 */
export interface PortForwardStat {
  /** 是否运行中 */
  running: boolean;
  /** 当前活跃连接数 */
  activeConnections: number;
  /** 累计连接数 */
  totalConnections: number;
  /** 累计入站流量(字节) */
  bytesIn: number;
  /** 累计出站流量(字节) */
  bytesOut: number;
  /** 本次启动时间 */
  startTime: Date | undefined;
}

/** 端口转发时间序列采样点 */
export interface PortForwardStatPoint {
  /** 采样时间 */
  time:
    | Date
    | undefined;
  /** 活跃连接数 */
  activeConnections: number;
  /** 累计入站流量(字节) */
  bytesIn: number;
  /** 累计出站流量(字节) */
  bytesOut: number;
}

export interface PortForwardInfo {
  /** 端口转发 id */
  id: string;
  /** 名称 */
  name: string;
  /** 所属用户 id */
  userId: string;
  /** 转发类型 */
  type: PortForwardType;
  /** 监听地址 */
  listenAddress: string;
  /** 监听端口 */
  listenPort: number;
  /** 目标地址 */
  targetAddress: string;
  /** 目标端口 */
  targetPort: number;
  /** 是否启用 */
  isEnable: boolean;
  /** 创建时间 */
  createTime:
    | Date
    | undefined;
  /** 更新时间 */
  updateTime:
    | Date
    | undefined;
  /** 运行错误 */
  error: string;
  /** 当前活跃连接数（运行中才有效） */
  activeConnections: number;
  /** 累计连接数（自本次启动起） */
  totalConnections: number;
  /** 累计入站流量(字节，客户端→目标) */
  bytesIn: number;
  /** 累计出站流量(字节，目标→客户端) */
  bytesOut: number;
}
