// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: v1/oidc.proto

/* eslint-disable */

export const protobufPackage = "v1";

/** OIDC 服务端配置 */
export interface OIDCConfig {
  /** 是否启用 OIDC 服务端 */
  enabled: boolean;
  /** Issuer URL；为空时服务端会按当前请求域名推导 */
  issuerUrl: string;
  /** Access Token 有效期，单位秒 */
  accessTokenTtlSeconds: number;
  /** ID Token 有效期，单位秒 */
  idTokenTtlSeconds: number;
  /** Authorization Code 有效期，单位秒 */
  authorizationCodeTtlSeconds: number;
  /** 根据 Issuer URL 自动生成的 OIDC 端点配置 */
  endpoints: OIDCEndpoints | undefined;
}

/** OIDC 客户端接入所需端点信息 */
export interface OIDCEndpoints {
  /** Provider 名称 */
  providerName: string;
  /** Issuer URL */
  issuerUrl: string;
  /** Discovery URL */
  discoveryUrl: string;
  /** 授权端点 URL */
  authorizeUrl: string;
  /** Token 端点 URL */
  tokenUrl: string;
  /** UserInfo 端点 URL */
  userinfoUrl: string;
  /** JWKS 端点 URL */
  jwksUrl: string;
  /** 默认 scopes */
  scopes: string;
  /** momoko 前端授权回调页路径 */
  frontendCallbackPath: string;
  /** Token 端点客户端认证方式 */
  tokenEndpointAuthMethod: string;
  /** 推荐客户端配置的时钟偏移容忍秒数 */
  clockSkewSeconds: number;
  /** 支持的 ID Token 签名算法 */
  allowedIdTokenSigningAlgs: string;
}

/** 获取 OIDC 配置请求 */
export interface OIDCConfigRequest {
}

/** 获取 OIDC 配置响应 */
export interface OIDCConfigResponse {
  /** OIDC 服务端配置 */
  config: OIDCConfig | undefined;
}

/** 更新 OIDC 配置请求 */
export interface UpdateOIDCConfigRequest {
  /** 是否启用 OIDC 服务端 */
  enabled: boolean;
  /** Issuer URL；建议配置为当前 momoko 对外访问域名 */
  issuerUrl: string;
  /** Access Token 有效期，单位秒；小于等于 0 时使用默认值 */
  accessTokenTtlSeconds: number;
  /** ID Token 有效期，单位秒；小于等于 0 时使用默认值 */
  idTokenTtlSeconds: number;
  /** Authorization Code 有效期，单位秒；小于等于 0 时使用默认值 */
  authorizationCodeTtlSeconds: number;
}

/** 更新 OIDC 配置响应 */
export interface UpdateOIDCConfigResponse {
  /** 更新后的 OIDC 服务端配置 */
  config: OIDCConfig | undefined;
}

/** OIDC 客户端信息 */
export interface OIDCClientInfo {
  /** 客户端记录 id */
  id: string;
  /** 客户端名称 */
  name: string;
  /** Client ID */
  clientId: string;
  /** Client Secret；列表接口返回脱敏值，创建/刷新接口返回完整值 */
  clientSecret: string;
  /** 允许的回调地址 */
  redirectUris: string[];
  /** 允许的 scopes，必须包含 openid */
  scopes: string[];
  /** 是否启用 */
  active: boolean;
  /** 创建时间 */
  createTime:
    | Date
    | undefined;
  /** 更新时间 */
  updateTime: Date | undefined;
}

/** 获取 OIDC 客户端列表请求 */
export interface ListOIDCClientsRequest {
  /** 页码 */
  page: number;
  /** 每页数量 */
  pageSize: number;
  /** 客户端名称关键字 */
  keywords?: string | undefined;
}

/** 获取 OIDC 客户端列表响应 */
export interface ListOIDCClientsResponse {
  /** 实际页码 */
  page: number;
  /** 实际每页数量 */
  pageSize: number;
  /** 总数 */
  total: number;
  /** 客户端列表 */
  clients: OIDCClientInfo[];
}

/** 创建 OIDC 客户端请求 */
export interface CreateOIDCClientRequest {
  /** 客户端名称 */
  name: string;
  /** 允许的回调地址 */
  redirectUris: string[];
  /** 允许的 scopes；为空时使用 openid email profile */
  scopes: string[];
  /** 是否启用 */
  active: boolean;
}

/** 创建 OIDC 客户端响应 */
export interface CreateOIDCClientResponse {
  /** 新建客户端信息；包含完整 Client Secret */
  client: OIDCClientInfo | undefined;
}

/** 更新 OIDC 客户端请求 */
export interface UpdateOIDCClientRequest {
  /** 客户端记录 id */
  id: string;
  /** 客户端名称 */
  name: string;
  /** 允许的回调地址 */
  redirectUris: string[];
  /** 允许的 scopes；必须包含 openid */
  scopes: string[];
  /** 是否启用 */
  active: boolean;
}

/** 更新 OIDC 客户端响应 */
export interface UpdateOIDCClientResponse {
  /** 更新后的客户端信息；Client Secret 为脱敏值 */
  client: OIDCClientInfo | undefined;
}

/** 删除 OIDC 客户端请求 */
export interface DeleteOIDCClientRequest {
  /** 客户端记录 id */
  id: string;
}

/** 删除 OIDC 客户端响应 */
export interface DeleteOIDCClientResponse {
}

/** 刷新 OIDC Client Secret 请求 */
export interface RefreshOIDCClientSecretRequest {
  /** 客户端记录 id */
  id: string;
}

/** 刷新 OIDC Client Secret 响应 */
export interface RefreshOIDCClientSecretResponse {
  /** 刷新后的客户端信息；包含新的完整 Client Secret */
  client: OIDCClientInfo | undefined;
}

/** 获取 OIDC 授权页展示信息请求 */
export interface OIDCAuthorizationInfoRequest {
  /** 授权响应类型；当前仅支持 code */
  responseType: string;
  /** Client ID */
  clientId: string;
  /** 回调地址，必须命中客户端配置中的 redirect_uris */
  redirectUri: string;
  /** 请求 scopes，必须包含 openid */
  scope: string;
}

/** OIDC 授权页展示信息 */
export interface OIDCAuthorizationInfo {
  /** 客户端名称，用于授权确认页展示 */
  clientName: string;
  /** Client ID，用于排查第三方接入配置 */
  clientId: string;
  /** 当前授权请求的回调地址 */
  redirectUri: string;
  /** 当前授权请求的 scopes */
  scope: string;
}

/** 获取 OIDC 授权页展示信息响应 */
export interface OIDCAuthorizationInfoResponse {
  /** 授权页展示信息 */
  info: OIDCAuthorizationInfo | undefined;
}

/** 创建 OIDC 授权码请求 */
export interface CreateOIDCAuthorizationCodeRequest {
  /** 授权响应类型；当前仅支持 code */
  responseType: string;
  /** Client ID */
  clientId: string;
  /** 回调地址，必须命中客户端配置中的 redirect_uris */
  redirectUri: string;
  /** 请求 scopes，必须包含 openid */
  scope: string;
  /** 客户端透传状态值 */
  state: string;
  /** 客户端 nonce；会写入 ID Token */
  nonce: string;
  /** PKCE code challenge */
  codeChallenge: string;
  /** PKCE code challenge method，支持 plain 和 S256 */
  codeChallengeMethod: string;
}

/** 创建 OIDC 授权码响应 */
export interface CreateOIDCAuthorizationCodeResponse {
  /** 携带 code 和 state 的第三方客户端回调地址 */
  redirectUrl: string;
}
