// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.0
// source: v1/openssh.proto

/* eslint-disable */

export const protobufPackage = "v1";

export enum SSHAuthType {
  /** SSH_AUTH_TYPE_UNSPECIFIED - 未指定 */
  SSH_AUTH_TYPE_UNSPECIFIED = "SSH_AUTH_TYPE_UNSPECIFIED",
  /** SSH_AUTH_TYPE_PASSWORD - 密码 */
  SSH_AUTH_TYPE_PASSWORD = "SSH_AUTH_TYPE_PASSWORD",
  /** SSH_AUTH_TYPE_KEY - 私钥 */
  SSH_AUTH_TYPE_KEY = "SSH_AUTH_TYPE_KEY",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum SSHHostAccessRole {
  /** SSH_HOST_ACCESS_ROLE_UNSPECIFIED - 未指定 */
  SSH_HOST_ACCESS_ROLE_UNSPECIFIED = "SSH_HOST_ACCESS_ROLE_UNSPECIFIED",
  /** SSH_HOST_ACCESS_ROLE_OWNER - 创建者 */
  SSH_HOST_ACCESS_ROLE_OWNER = "SSH_HOST_ACCESS_ROLE_OWNER",
  /** SSH_HOST_ACCESS_ROLE_SHARED - 被分享者 */
  SSH_HOST_ACCESS_ROLE_SHARED = "SSH_HOST_ACCESS_ROLE_SHARED",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface GetSSHHostsRequest {
  /** page */
  page: number;
  /** page size */
  pageSize: number;
  /** 名称/标签/主机地址 */
  keywords?:
    | string
    | undefined;
  /** 主机地址 */
  host?: string | undefined;
}

export interface GetSSHHostsResponse {
  /** actual page */
  page: number;
  /** actual page size */
  pageSize: number;
  /** 总数 */
  total: number;
  /** 列表 */
  infos: SSHHostInfo[];
}

export interface CreateSSHHostRequest {
  /** 名称 */
  name: string;
  /** 主机地址 */
  host: string;
  /** 端口 */
  port: number;
  /** 用户名 */
  username: string;
  /** 认证方式 */
  authType: SSHAuthType;
  /** 密码认证时填写 */
  password: string;
  /** 密钥认证时填写 */
  privateKey: string;
  /** 私钥口令 */
  passphrase: string;
  /** 主机指纹 */
  fingerprint: string;
  /** 备注 */
  remark: string;
  /** 标签 */
  tags: string;
  /** 分享给指定用户 */
  sharedUserIds: string[];
}

export interface CreateSSHHostResponse {
  /** SSH 服务端详情 */
  info: SSHHostInfo | undefined;
}

export interface GetSSHHostInfoRequest {
  /** SSH 服务端 id */
  id: string;
}

export interface GetSSHHostInfoResponse {
  /** SSH 服务端详情 */
  info: SSHHostInfo | undefined;
}

export interface UpdateSSHHostRequest {
  /** SSH 服务端 id */
  id: string;
  /** 名称 */
  name?:
    | string
    | undefined;
  /** 主机地址 */
  host?:
    | string
    | undefined;
  /** 端口 */
  port?:
    | number
    | undefined;
  /** 用户名 */
  username?:
    | string
    | undefined;
  /** 认证方式 */
  authType?:
    | SSHAuthType
    | undefined;
  /** 密码认证时填写 */
  password?:
    | string
    | undefined;
  /** 密钥认证时填写 */
  privateKey?:
    | string
    | undefined;
  /** 私钥口令 */
  passphrase?:
    | string
    | undefined;
  /** 主机指纹 */
  fingerprint?:
    | string
    | undefined;
  /** 备注 */
  remark?:
    | string
    | undefined;
  /** 标签 */
  tags?: string | undefined;
}

export interface UpdateSSHHostResponse {
  /** SSH 服务端详情 */
  info: SSHHostInfo | undefined;
}

export interface DeleteSSHHostRequest {
  /** SSH 服务端 id */
  id: string;
}

export interface DeleteSSHHostResponse {
}

export interface ShareSSHHostRequest {
  /** SSH 服务端 id */
  id: string;
  /** 分享给指定用户；传空数组表示取消全部分享 */
  userIds: string[];
}

export interface ShareSSHHostResponse {
  /** SSH 服务端详情 */
  info: SSHHostInfo | undefined;
}

/**
 * 连通性测试请求（不持久化状态）。
 * 编辑弹窗：传 id + 当前表单草稿字段（空凭据表示沿用库中已存凭据）。
 * 新建弹窗：不传 id，必须带齐 host/username/凭据。
 */
export interface TestSSHHostRequest {
  /** 已有主机 id（可选；编辑弹窗带上以便空凭据时回落到库中配置） */
  id?:
    | string
    | undefined;
  /** 主机地址 */
  host?:
    | string
    | undefined;
  /** 端口 */
  port?:
    | number
    | undefined;
  /** 用户名 */
  username?:
    | string
    | undefined;
  /** 认证方式 */
  authType?:
    | SSHAuthType
    | undefined;
  /** 密码（密码认证；空=沿用已存） */
  password?:
    | string
    | undefined;
  /** 私钥（密钥认证；空=沿用已存） */
  privateKey?:
    | string
    | undefined;
  /** 私钥口令 */
  passphrase?:
    | string
    | undefined;
  /** 主机指纹（空=沿用已存） */
  fingerprint?: string | undefined;
}

export interface TestSSHHostResponse {
  /** 是否连通 */
  ok: boolean;
  /** 测试结果说明 */
  message: string;
  /** 探测到的服务端主机指纹（成功时可能有） */
  fingerprint: string;
}

export interface SSHHostInfo {
  /** SSH 服务端 id */
  id: string;
  /** 名称 */
  name: string;
  /** 主机地址 */
  host: string;
  /** 端口 */
  port: number;
  /** 用户名 */
  username: string;
  /** 认证方式 */
  authType: SSHAuthType;
  /** 主机指纹 */
  fingerprint: string;
  /** 备注 */
  remark: string;
  /** 标签 */
  tags: string;
  /** 所属用户 id */
  ownerUserId: string;
  /** 分享用户信息 */
  sharedUsers: SSHHostSharedUser[];
  /** 当前用户访问身份 */
  accessRole: SSHHostAccessRole;
  /** WebSocket 路径 */
  wsPath: string;
  /** 创建时间 */
  createTime:
    | Date
    | undefined;
  /** 更新时间 */
  updateTime: Date | undefined;
}

export interface SSHHostSharedUser {
  /** 用户id */
  userId: string;
  /** 用户名称 */
  name: string;
}
