// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: v1/sub2api.proto

/* eslint-disable */

export const protobufPackage = "v1";

export interface PublicSub2APIHomeRequest {
}

export interface PublicSub2APIHomeResponse {
  home: Sub2APIHome | undefined;
}

export interface GetSub2APIConfigRequest {
}

export interface GetSub2APIConfigResponse {
  config: Sub2APIConfig | undefined;
}

export interface UpdateSub2APIConfigRequest {
  config: Sub2APIConfig | undefined;
}

export interface UpdateSub2APIConfigResponse {
  config: Sub2APIConfig | undefined;
}

export interface TestSub2APIConnectionRequest {
  config: Sub2APIConfig | undefined;
}

export interface TestSub2APIConnectionResponse {
  connected: boolean;
  message: string;
}

export interface SyncSub2APIUsageRequest {
  /** 是否强制全量同步 */
  full: boolean;
}

export interface SyncSub2APIUsageResponse {
  snapshot: Sub2APIUsageSnapshot | undefined;
}

export interface GetSub2APISnapshotRequest {
}

export interface GetSub2APISnapshotResponse {
  snapshot: Sub2APIUsageSnapshot | undefined;
}

export interface GetSub2APIStatsRequest {
  /** 统计区间天数：<=1 表示今日，否则为最近 N 天 */
  rangeDays: number;
}

export interface GetSub2APIStatsResponse {
  stats: Sub2APIStats | undefined;
}

export interface GetSub2APIAdminStatsRequest {
  /**
   * 统计时间段（Unix 毫秒，精度到分钟）：start_time 起、end_time 止。
   * start_time <= 0 时按今日 0 点，end_time <= 0 时按当前时间。
   */
  startTime: number;
  endTime: number;
}

export interface GetSub2APIAdminStatsResponse {
  stats: Sub2APIStats | undefined;
}

export interface GetSub2APIRecentRequestsRequest {
  /** 统计时间段（Unix 毫秒，精度到分钟）：与管理端用量概览一致。 */
  startTime: number;
  endTime: number;
  /** 页码（从 1 起）与每页条数。 */
  page: number;
  pageSize: number;
}

export interface GetSub2APIRecentRequestsResponse {
  recentRequests: Sub2APIRecentRequest[];
  total: number;
  page: number;
  pageSize: number;
}

export interface Sub2APIStats {
  rangeDays: number;
  rangeLabel: string;
  requestCount: number;
  successCount: number;
  successRate: number;
  tokenCount: number;
  averageLatencyMs: number;
  averageTps: number;
  trend: Sub2APITrendPoint[];
  models: Sub2APITopItem[];
  endpoints: Sub2APITopItem[];
  /** UA（User-Agent）维度用量明细，按使用数量降序 */
  userAgents: Sub2APITopItem[];
}

/** 仅包含连接与展示配置，公告/时间线为独立资源。 */
export interface Sub2APIConfig {
  homeEnabled: boolean;
  syncEnabled: boolean;
  baseUrl: string;
  adminApiKey: string;
  consoleUrl: string;
  title: string;
  subtitle: string;
  introduction: string;
  syncIntervalMinutes: number;
  historyDays: number;
  pageSize: number;
  /** 允许调用 momoko 生图的 sub2api 站点 origin 列表（留空表示不限制） */
  allowedSrcHosts: string[];
  /** 是否启用生图功能 */
  imageEnabled: boolean;
  /** 是否开启站点白名单校验 */
  srcHostWhitelistEnabled: boolean;
}

export interface Sub2APIHome {
  enabled: boolean;
  consoleUrl: string;
  title: string;
  subtitle: string;
  introduction: string;
  snapshot: Sub2APIUsageSnapshot | undefined;
  announcements: Sub2APIAnnouncement[];
  timeline: Sub2APITimelineItem[];
}

export interface Sub2APIAnnouncement {
  id: string;
  title: string;
  content: string;
  level: string;
  publishedAt: Date | undefined;
  pinned: boolean;
}

export interface Sub2APITimelineItem {
  id: string;
  title: string;
  content: string;
  category: string;
  publishedAt: Date | undefined;
}

/** 公告管理消息 */
export interface ListSub2APIAnnouncementsRequest {
}

export interface ListSub2APIAnnouncementsResponse {
  announcements: Sub2APIAnnouncement[];
}

export interface CreateSub2APIAnnouncementRequest {
  title: string;
  content: string;
  level: string;
  pinned: boolean;
  publishedAt: Date | undefined;
}

export interface UpdateSub2APIAnnouncementRequest {
  id: string;
  title: string;
  content: string;
  level: string;
  pinned: boolean;
  publishedAt: Date | undefined;
}

export interface Sub2APIAnnouncementResponse {
  announcement: Sub2APIAnnouncement | undefined;
}

export interface DeleteSub2APIAnnouncementRequest {
  id: string;
}

export interface DeleteSub2APIAnnouncementResponse {
}

/** 时间线管理消息 */
export interface ListSub2APITimelineRequest {
}

export interface ListSub2APITimelineResponse {
  timeline: Sub2APITimelineItem[];
}

export interface CreateSub2APITimelineItemRequest {
  title: string;
  content: string;
  category: string;
  publishedAt: Date | undefined;
}

export interface UpdateSub2APITimelineItemRequest {
  id: string;
  title: string;
  content: string;
  category: string;
  publishedAt: Date | undefined;
}

export interface Sub2APITimelineItemResponse {
  item: Sub2APITimelineItem | undefined;
}

export interface DeleteSub2APITimelineItemRequest {
  id: string;
}

export interface DeleteSub2APITimelineItemResponse {
}

export interface Sub2APIUsageSnapshot {
  configured: boolean;
  status: string;
  error: string;
  lastSyncTime: Date | undefined;
  nextSyncTime: Date | undefined;
  latestRecordTime: Date | undefined;
  syncedRecords: number;
  totalRecords: number;
  requestCount: number;
  successCount: number;
  successRate: number;
  averageLatencyMs: number;
  tokenCount: number;
  todayRequestCount: number;
  todaySuccessCount: number;
  todaySuccessRate: number;
  todayAverageLatencyMs: number;
  todayTokenCount: number;
  dataRange: string;
  generatedAt: Date | undefined;
  trend: Sub2APITrendPoint[];
  modelUsage: Sub2APITopItem[];
  endpointUsage: Sub2APITopItem[];
  recentRequests: Sub2APIRecentRequest[];
  /** 最近滑动窗口内的真实吞吐（锚定最新记录时间，避免随墙钟衰减） */
  recentTps: number;
  recentQps: number;
  recentWindowSeconds: number;
  /** 当日按时间分桶的成功率/生成速度序列（用于首页随时间移动的曲线） */
  todaySeries: Sub2APITimePoint[];
}

export interface Sub2APITimePoint {
  time: Date | undefined;
  requestCount: number;
  successRate: number;
  avgTps: number;
}

export interface Sub2APITrendPoint {
  date: string;
  requestCount: number;
  successCount: number;
  successRate: number;
  averageLatencyMs: number;
  tokenCount: number;
}

export interface Sub2APITopItem {
  name: string;
  requestCount: number;
  tokenCount: number;
  successRate: number;
  /** 该模型的平均 token 生成速度（输出token/秒，按请求平均，不含缓存） */
  avgTps: number;
}

export interface Sub2APIRecentRequest {
  requestId: string;
  model: string;
  endpoint: string;
  status: string;
  success: boolean;
  latencyMs: number;
  tokenCount: number;
  requestTime:
    | Date
    | undefined;
  /** 详情字段（成功请求） */
  cost: number;
  /** 首 token 延迟（毫秒） */
  firstTokenMs: number;
  /** 推理强度 */
  reasoningEffort: string;
  /** 账号名称 */
  accountName: string;
  /** 详情字段（失败/上游错误请求） */
  errorMessage: string;
  /** HTTP 状态码 */
  httpStatus: number;
}
