// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.0
// source: v1/sub2api_imagine.proto

/* eslint-disable */

export const protobufPackage = "v1";

export interface ListImageGenApiKeysRequest {
}

export interface ImageGenApiKeySummary {
  id: string;
  name: string;
  groupId: string;
  groupName: string;
  platform: string;
}

export interface ListImageGenApiKeysResponse {
  apiKeys: ImageGenApiKeySummary[];
}

export interface ListImageGenModelsRequest {
  apiKeyId: string;
}

export interface ImageGenModel {
  id: string;
  displayName: string;
}

export interface ListImageGenModelsResponse {
  models: ImageGenModel[];
}

export interface ListImageGenGenerationsRequest {
  /** 最近多少条，<=0 时取默认 50 */
  limit: number;
}

export interface ListImageGenGenerationsResponse {
  generations: ImageGenGeneration[];
}

export interface CreateImageGenGenerationRequest {
  model: string;
  prompt: string;
  size: string;
  n: number;
  quality: string;
  outputFormat: string;
  /**
   * 源图：整张图片，base64 data URL（data:image/png;base64,...）。
   * 带 source_image 即图生图（走 /v1/images/edits），否则文生图（走 /v1/images/generations）。
   */
  sourceImage: string;
  apiKeyId: string;
}

export interface GetImageGenGenerationRequest {
  id: string;
}

export interface ImageGenGenerationResponse {
  generation: ImageGenGeneration | undefined;
}

export interface DeleteImageGenGenerationRequest {
  id: string;
}

export interface DeleteImageGenGenerationResponse {
}

export interface ImageGenGeneration {
  id: string;
  userId: string;
  mode: string;
  model: string;
  prompt: string;
  size: string;
  n: number;
  quality: string;
  outputFormat: string;
  /** pending | completed | failed */
  status: string;
  errorMessage: string;
  latencyMs: number;
  resultCount: number;
  apiKeyId: string;
  startedAt: Date | undefined;
  finishedAt: Date | undefined;
  createdAt: Date | undefined;
  images: ImageGenImage[];
}

export interface ImageGenImage {
  id: string;
  generationId: string;
  filename: string;
  index: number;
  width: number;
  height: number;
  mimeType: string;
  sizeBytes: number;
  revisedPrompt: string;
  createdAt: Date | undefined;
}
