// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: v1/tunnel.proto

/* eslint-disable */

export const protobufPackage = "v1";

export enum TunnelType {
  /** TUNNEL_TYPE_UNSPECIFIED - 未指定 */
  TUNNEL_TYPE_UNSPECIFIED = "TUNNEL_TYPE_UNSPECIFIED",
  /** TUNNEL_TYPE_TCP - TCP */
  TUNNEL_TYPE_TCP = "TUNNEL_TYPE_TCP",
  /** TUNNEL_TYPE_UDP - UDP */
  TUNNEL_TYPE_UDP = "TUNNEL_TYPE_UDP",
  /** TUNNEL_TYPE_HTTP - HTTP */
  TUNNEL_TYPE_HTTP = "TUNNEL_TYPE_HTTP",
  /** TUNNEL_TYPE_HTTPS - HTTPS */
  TUNNEL_TYPE_HTTPS = "TUNNEL_TYPE_HTTPS",
  /** TUNNEL_TYPE_STCP - STCP */
  TUNNEL_TYPE_STCP = "TUNNEL_TYPE_STCP",
  /** TUNNEL_TYPE_XTCP - XTCP */
  TUNNEL_TYPE_XTCP = "TUNNEL_TYPE_XTCP",
  /** TUNNEL_TYPE_TCPMUX - TCPMUX */
  TUNNEL_TYPE_TCPMUX = "TUNNEL_TYPE_TCPMUX",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum TunnelStatus {
  /** TUNNEL_STATUS_UNSPECIFIED - 未指定 */
  TUNNEL_STATUS_UNSPECIFIED = "TUNNEL_STATUS_UNSPECIFIED",
  /** TUNNEL_STATUS_PENDING - 待连接（已启用但 frpc 尚未连入） */
  TUNNEL_STATUS_PENDING = "TUNNEL_STATUS_PENDING",
  /** TUNNEL_STATUS_ONLINE - 在线（frpc 已连接且 proxy 在线） */
  TUNNEL_STATUS_ONLINE = "TUNNEL_STATUS_ONLINE",
  /** TUNNEL_STATUS_OFFLINE - 离线（未启用或已下线） */
  TUNNEL_STATUS_OFFLINE = "TUNNEL_STATUS_OFFLINE",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface ListTunnelsRequest {
  /** page */
  page: number;
  /** page size */
  pageSize: number;
  /** 名称/域名关键词 */
  keywords?:
    | string
    | undefined;
  /** 代理类型 */
  type?:
    | TunnelType
    | undefined;
  /** 是否启用 */
  isEnable?: boolean | undefined;
}

export interface ListTunnelsResponse {
  /** actual page */
  page: number;
  /** actual page size */
  pageSize: number;
  /** 总数 */
  total: number;
  /** 列表 */
  infos: TunnelInfo[];
}

export interface CreateTunnelRequest {
  /** 名称（frp proxy 名称，全局唯一） */
  name: string;
  /** 代理类型 */
  type: TunnelType;
  /** 公共端口（tcp/udp/tcpmux） */
  remotePort: number;
  /** 自定义域名（http/https，逗号分隔） */
  customDomains: string;
  /** 子域名（http/https） */
  subdomain: string;
  /** frpc 端本地地址 */
  localIp: string;
  /** frpc 端本地端口 */
  localPort: number;
  /** 允许的 frpc user，逗号分隔；空=不限制 */
  allowUsers: string;
  /** 是否启用 */
  isEnable: boolean;
  /** 带宽上限（限速，如 "1MB"/"100KB"）；客户端声明带宽不得超过该值，空=不限 */
  maxBandwidth: string;
  /** 活跃连接数上限（momoko 在每条用户连接时校验，超出即拒绝），0=不限 */
  maxActiveConns: number;
}

export interface CreateTunnelResponse {
  /** 隧道详情 */
  info: TunnelInfo | undefined;
}

export interface GetTunnelRequest {
  /** 隧道 id */
  id: string;
}

export interface GetTunnelResponse {
  /** 隧道详情 */
  info: TunnelInfo | undefined;
}

export interface UpdateTunnelRequest {
  /** 隧道 id */
  id: string;
  /** 名称 */
  name?:
    | string
    | undefined;
  /** 代理类型 */
  type?:
    | TunnelType
    | undefined;
  /** 公共端口 */
  remotePort?:
    | number
    | undefined;
  /** 自定义域名 */
  customDomains?:
    | string
    | undefined;
  /** 子域名 */
  subdomain?:
    | string
    | undefined;
  /** 本地地址 */
  localIp?:
    | string
    | undefined;
  /** 本地端口 */
  localPort?:
    | number
    | undefined;
  /** 允许的 frpc user */
  allowUsers?:
    | string
    | undefined;
  /** 是否启用 */
  isEnable?:
    | boolean
    | undefined;
  /** 带宽上限（限速，如 "1MB"；空=不限） */
  maxBandwidth?:
    | string
    | undefined;
  /** 活跃连接数上限，0=不限 */
  maxActiveConns?: number | undefined;
}

export interface UpdateTunnelResponse {
  /** 隧道详情 */
  info: TunnelInfo | undefined;
}

export interface DeleteTunnelRequest {
  /** 隧道 id */
  id: string;
}

export interface DeleteTunnelResponse {
}

export interface GetTunnelStatsRequest {
  /** 隧道 id */
  id: string;
  /** 起始时间(Unix 毫秒)，不传或<=0 时默认结束时间往前 1 小时 */
  startTimeMs: number;
  /** 结束时间(Unix 毫秒)，不传或<=0 时默认当前时间 */
  endTimeMs: number;
}

export interface GetTunnelStatsResponse {
  /** 当前快照 */
  snapshot:
    | TunnelStat
    | undefined;
  /** 时间序列样本（按时间升序，流量为累计值） */
  points: TunnelStatPoint[];
  /** 采样间隔(秒) */
  sampleIntervalSeconds: number;
}

export interface GetFrpsConfigRequest {
}

export interface GetFrpsConfigResponse {
  /** frps 实例配置 */
  config: FrpsConfig | undefined;
}

export interface UpdateFrpsConfigRequest {
  /** frps 实例配置 */
  config: FrpsConfig | undefined;
}

export interface UpdateFrpsConfigResponse {
  /** frps 实例配置 */
  config: FrpsConfig | undefined;
}

/** 隧道实时快照 */
export interface TunnelStat {
  /** 是否在线（frpc 已连接且 proxy 在线） */
  online: boolean;
  /** 当前活跃连接数 */
  activeConnections: number;
  /** 当日累计入站流量(字节) */
  bytesIn: number;
  /** 当日累计出站流量(字节) */
  bytesOut: number;
  /** 最近一次上线时间 */
  lastStartTime: Date | undefined;
}

/** 隧道时间序列采样点 */
export interface TunnelStatPoint {
  /** 采样时间 */
  time:
    | Date
    | undefined;
  /** 活跃连接数 */
  activeConnections: number;
  /** 累计入站流量(字节) */
  bytesIn: number;
  /** 累计出站流量(字节) */
  bytesOut: number;
}

export interface TunnelInfo {
  /** 隧道 id */
  id: string;
  /** 名称 */
  name: string;
  /** 所属用户 id */
  userId: string;
  /** 代理类型 */
  type: TunnelType;
  /** 公共端口（tcp/udp/tcpmux） */
  remotePort: number;
  /** 自定义域名（http/https） */
  customDomains: string;
  /** 子域名（http/https） */
  subdomain: string;
  /** frpc 端本地地址 */
  localIp: string;
  /** frpc 端本地端口 */
  localPort: number;
  /** 每隧道认证凭证（仅 owner 可见） */
  credential: string;
  /** 允许的 frpc user */
  allowUsers: string;
  /** 是否启用 */
  isEnable: boolean;
  /** 运行状态 */
  status: TunnelStatus;
  /** 创建时间 */
  createTime:
    | Date
    | undefined;
  /** 更新时间 */
  updateTime:
    | Date
    | undefined;
  /** 当前活跃连接数（在线才有效） */
  activeConnections: number;
  /** 当日累计入站流量(字节) */
  bytesIn: number;
  /** 当日累计出站流量(字节) */
  bytesOut: number;
  /** 带宽上限（限速，如 "1MB"；空=不限） */
  maxBandwidth: string;
  /** 活跃连接数上限，0=不限 */
  maxActiveConns: number;
}

/**
 * frps 实例配置（实例级，非逐条隧道规则）。
 * 注：无 auth_token。frps 自身 Auth 中性化（空 token），不作为统一认证；
 * 每隧道独立凭证存于隧道规则，由插件 Login/NewProxy 校验。
 */
export interface FrpsConfig {
  /** 是否启用 frps（false 时不启动） */
  isEnable: boolean;
  /** 监听地址，默认 0.0.0.0 */
  bindAddr: string;
  /** frpc 连接端口（frps 主端口），默认 7000 */
  bindPort: number;
  /** http 代理 vhost 端口，0=不监听 */
  vhostHttpPort: number;
  /** https 代理 vhost 端口，0=不监听 */
  vhostHttpsPort: number;
  /** kcp 传输端口，0=不监听 */
  kcpBindPort: number;
  /** quic 传输端口，0=不监听 */
  quicBindPort: number;
  /** 子域名根域（http/https subdomain 用） */
  subdomainHost: string;
  /** 统计采样间隔(秒) */
  statSampleInterval: number;
  /** 对外可达的服务器地址（生成 frpc 配置时填入 serverAddr；空=回退 bind_addr） */
  serverAddr: string;
}
