// Code generated by ent, DO NOT EDIT.

package fileupload

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the fileupload type in the database.
	Label = "file_upload"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldHash holds the string denoting the hash field in the database.
	FieldHash = "hash"
	// FieldPath holds the string denoting the path field in the database.
	FieldPath = "path"
	// FieldFileName holds the string denoting the file_name field in the database.
	FieldFileName = "file_name"
	// FieldFileSize holds the string denoting the file_size field in the database.
	FieldFileSize = "file_size"
	// FieldChunkSize holds the string denoting the chunk_size field in the database.
	FieldChunkSize = "chunk_size"
	// FieldTotalChunks holds the string denoting the total_chunks field in the database.
	FieldTotalChunks = "total_chunks"
	// FieldCompleted holds the string denoting the completed field in the database.
	FieldCompleted = "completed"
	// FieldCancel holds the string denoting the cancel field in the database.
	FieldCancel = "cancel"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeChunks holds the string denoting the chunks edge name in mutations.
	EdgeChunks = "chunks"
	// Table holds the table name of the fileupload in the database.
	Table = "file_uploads"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "file_uploads"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// ChunksTable is the table that holds the chunks relation/edge.
	ChunksTable = "file_upload_chunks"
	// ChunksInverseTable is the table name for the FileUploadChunk entity.
	// It exists in this package in order to avoid circular dependency with the "fileuploadchunk" package.
	ChunksInverseTable = "file_upload_chunks"
	// ChunksColumn is the table column denoting the chunks relation/edge.
	ChunksColumn = "upload_id"
)

// Columns holds all SQL columns for fileupload fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldHash,
	FieldPath,
	FieldFileName,
	FieldFileSize,
	FieldChunkSize,
	FieldTotalChunks,
	FieldCompleted,
	FieldCancel,
	FieldUserID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultCompleted holds the default value on creation for the "completed" field.
	DefaultCompleted bool
	// DefaultCancel holds the default value on creation for the "cancel" field.
	DefaultCancel bool
)

// OrderOption defines the ordering options for the FileUpload queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByHash orders the results by the hash field.
func ByHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHash, opts...).ToFunc()
}

// ByPath orders the results by the path field.
func ByPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPath, opts...).ToFunc()
}

// ByFileName orders the results by the file_name field.
func ByFileName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileName, opts...).ToFunc()
}

// ByFileSize orders the results by the file_size field.
func ByFileSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileSize, opts...).ToFunc()
}

// ByChunkSize orders the results by the chunk_size field.
func ByChunkSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChunkSize, opts...).ToFunc()
}

// ByTotalChunks orders the results by the total_chunks field.
func ByTotalChunks(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalChunks, opts...).ToFunc()
}

// ByCompleted orders the results by the completed field.
func ByCompleted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCompleted, opts...).ToFunc()
}

// ByCancel orders the results by the cancel field.
func ByCancel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCancel, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByChunksCount orders the results by chunks count.
func ByChunksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newChunksStep(), opts...)
	}
}

// ByChunks orders the results by chunks terms.
func ByChunks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChunksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
	)
}
func newChunksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChunksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, ChunksTable, ChunksColumn),
	)
}
