server:
  http:
    addr: 0.0.0.0:22633
    timeout: 5s
  grpc:
    addr: 0.0.0.0:22733
    timeout: 5s
data:
  database:
    driver: sqlite3
    source: file:./data/momoko.db?_pragma=foreign_keys(1)
auth:
  secret: gucooing.auth