// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.31.1
// source: v1/auth.proto

/* eslint-disable */
import type { Duration } from "../google/protobuf/duration";

export const protobufPackage = "v1";

/** 账号登录请求 */
export interface LoginRequest {
  /** 登录密码 */
  password: string;
  /** 用户名登录 */
  username?:
    | string
    | undefined;
  /** 邮箱登录 */
  email?:
    | string
    | undefined;
  /** 登录设备 */
  device: string;
  /** ip地址 */
  ip: string;
}

/** 账号登录响应 */
export interface LoginResponse {
  /** token */
  accessToken: string;
  /** 刷新token */
  refreshToken: string;
  /** token 有效时间 */
  expiresIn: Duration | undefined;
}

/** 刷新token请求 */
export interface RefreshRequest {
  /** 刷新token */
  refreshToken: string;
}

/** 刷新token响应 */
export interface RefreshResponse {
  /** token */
  accessToken: string;
  /** 刷新token */
  refreshToken: string;
  /** token 有效时间 */
  expiresIn: Duration | undefined;
}

/** 获取登录设备请求 */
export interface DevicesRequest {
}

/** 获取登录设备响应 */
export interface DevicesResponse {
  /** 设备列表 */
  devices: LoginDevice[];
  /** 当前设备id */
  deviceId: string;
}

/** 登录设备信息 */
export interface LoginDevice {
  /** 登录时间 */
  loginTime:
    | Date
    | undefined;
  /** 登录设备 */
  device: string;
  /** 登录ip */
  ip: string;
  /** 设备id */
  deviceId: string;
  /** 会话id */
  sessionId: string;
  /** 最近一次刷新时间 */
  updateTime: Date | undefined;
}
