// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.31.1
// source: v1/instance.proto

/* eslint-disable */

export const protobufPackage = "v1";

/** 实例状态 */
export enum InstanceStatus {
  /** INSTANCE_STATUS_UNSPECIFIED - 未指定 */
  INSTANCE_STATUS_UNSPECIFIED = "INSTANCE_STATUS_UNSPECIFIED",
  /** INSTANCE_STATUS_STOPPED - 停止 */
  INSTANCE_STATUS_STOPPED = "INSTANCE_STATUS_STOPPED",
  /** INSTANCE_STATUS_RUNNING - 运行中 */
  INSTANCE_STATUS_RUNNING = "INSTANCE_STATUS_RUNNING",
  /** INSTANCE_STATUS_MAINTENANCE - 维护 */
  INSTANCE_STATUS_MAINTENANCE = "INSTANCE_STATUS_MAINTENANCE",
  UNRECOGNIZED = "UNRECOGNIZED",
}

/** 获取实例类型请求 */
export interface GetInstanceTypesRequest {
}

/** 获取实例类型响应 */
export interface GetInstanceTypesResponse {
  /** 类型列表 */
  types: InstanceTypeInfo[];
}

/** 创建实例类型请求 */
export interface CreateInstanceTypeRequest {
  /** 类型名称 */
  name: string;
}

/** 创建实例类型响应 */
export interface CreateInstanceTypeResponse {
  /** 实例信息 */
  type: InstanceTypeInfo | undefined;
}

/** 更新实例类型请求 */
export interface UpdateInstanceTypeRequest {
  /** 类型id */
  id: string;
  /** 类型名称 */
  name?:
    | string
    | undefined;
  /** 是否启用 */
  isEnable?: boolean | undefined;
}

/** 更新实例类型响应 */
export interface UpdateInstanceTypeResponse {
  /** 实例信息 */
  type: InstanceTypeInfo | undefined;
}

/** 删除实例类型请求 */
export interface DelInstanceTypeRequest {
  /** 类型id */
  id: string;
}

/** 删除实例类型响应 */
export interface DelInstanceTypeResponse {
}

/** 实例类型信息 */
export interface InstanceTypeInfo {
  /** 类型id */
  id: string;
  /** 类型名称 */
  name: string;
  /** 是否系统内置 */
  isSystem: boolean;
  /** 是否启用 */
  isEnable: boolean;
}

/** 获取终端详情请求 */
export interface GetTerminalInfoRequest {
}

/** 获取终端详情响应 */
export interface GetTerminalInfoResponse {
  /** 信息 */
  info: InstanceInfo | undefined;
}

/** 启动终端请求 */
export interface StartTerminalRequest {
}

/** 启动终端响应 */
export interface StartTerminalResponse {
}

/** 停止终端请求 */
export interface StopTerminalRequest {
}

/** 停止终端响应 */
export interface StopTerminalResponse {
}

/** 重启终端请求 */
export interface RestartTerminalRequest {
}

/** 重启终端响应 */
export interface RestartTerminalResponse {
}

/** 获取实例列表请求 */
export interface GetInstancesRequest {
  /** page */
  page: number;
  /** page size */
  pageSize: number;
  /** 实例名称/标签 */
  keywords?:
    | string
    | undefined;
  /** 类型 */
  type?:
    | string
    | undefined;
  /** 状态 */
  status?: InstanceStatus | undefined;
}

/** 获取实例列表响应 */
export interface GetInstancesResponse {
  /** actual page */
  page: number;
  /** actual page size */
  pageSize: number;
  /** 总数 */
  total: number;
  /** 列表 */
  infos: InstanceInfo[];
}

/** 创建实例请求 */
export interface CreateInstanceRequest {
  /** 实例名称 */
  name: string;
  /** 备注 */
  remark: string;
  /** 标签(,号隔开) */
  tags: string;
  /** 类型 */
  type: string;
  /** 所属用户id */
  userId: string;
  /** 启动命令 */
  startCommand: string;
  /** 实例路径 */
  instancePath: string;
  /** 停止命令 */
  stopCommand: string;
  /** 是否自启动 */
  autoStart: boolean;
  /** 环境变量(一行一个 如:GO_WANT_HELPER_PROCESS=1 */
  env: string[];
}

/** 创建实例响应 */
export interface CreateInstanceResponse {
  /** 实例详情 */
  info: InstanceInfo | undefined;
}

/** 获取实例详情请求 */
export interface GetInstanceInfoRequest {
  /** id */
  id: string;
}

/** 获取实例详情响应 */
export interface GetInstanceInfoResponse {
  /** 实例详情 */
  info: InstanceInfo | undefined;
}

/** 获取实例控制台详情请求 */
export interface GetInstanceTerminalInfoRequest {
  /** 实例id */
  id: string;
}

/** 获取实例控制台详情响应 */
export interface GetInstanceTerminalInfoResponse {
}

/** 启动实例请求 */
export interface StartInstanceRequest {
  /** 实例id */
  id: string;
}

/** 启动实例响应 */
export interface StartInstanceResponse {
  /** 实例详情 */
  info: InstanceInfo | undefined;
}

/** 停止实例请求 */
export interface StopInstanceRequest {
  /** 实例id */
  id: string;
  /** 是否强制停止 */
  force: boolean;
}

/** 停止实例响应 */
export interface StopInstanceResponse {
}

/** 重启实例请求 */
export interface RestartInstanceRequest {
  /** 实例id */
  id: string;
  /** 是否强制重启 */
  force: boolean;
}

/** 重启实例响应 */
export interface RestartInstanceResponse {
}

/** 删除实例请求 */
export interface DelInstanceRequest {
  /** 实例id */
  id: string;
}

/** 删除实例响应 */
export interface DelInstanceResponse {
}

export interface UpdateInstanceRequest {
  /** 实例id */
  id: string;
  /** 实例名称 */
  name?:
    | string
    | undefined;
  /** 备注 */
  remark?:
    | string
    | undefined;
  /** 标签(,号隔开) */
  tags?:
    | string
    | undefined;
  /** 类型 */
  type?:
    | string
    | undefined;
  /** 所属用户id */
  userId?:
    | string
    | undefined;
  /** 启动命令 */
  startCommand?:
    | string
    | undefined;
  /** 实例路径 */
  instancePath?:
    | string
    | undefined;
  /** ws路径(启动时才有 */
  wsPath?:
    | string
    | undefined;
  /** 停止命令 */
  stopCommand?:
    | string
    | undefined;
  /** 是否自启动 */
  autoStart?:
    | boolean
    | undefined;
  /** 环境变量(一行一个 如:GO_WANT_HELPER_PROCESS=1 */
  env: string[];
}

export interface UpdateInstanceResponse {
  /** 实例详情 */
  info: InstanceInfo | undefined;
}

/** 实例详情 */
export interface InstanceInfo {
  /** 实例id */
  id: string;
  /** 实例名称 */
  name: string;
  /** 实例状态 */
  status: InstanceStatus;
  /** 启动时间 */
  startTime:
    | Date
    | undefined;
  /** 创建时间 */
  createTime:
    | Date
    | undefined;
  /** 备注 */
  remark: string;
  /** 标签(,号隔开) */
  tags: string;
  /** 类型 */
  type: string;
  /** 所属用户id */
  userId: string;
  /** 启动命令 */
  startCommand: string;
  /** 实例路径 */
  instancePath: string;
  /** ws路径(启动时才有 */
  wsPath: string;
  /** 停止命令 */
  stopCommand: string;
  /** 是否自启动 */
  autoStart: boolean;
  /** 环境变量(一行一个 如:GO_WANT_HELPER_PROCESS=1 */
  env: string[];
}
