// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.31.1
// source: v1/system.proto

/* eslint-disable */

export const protobufPackage = "v1";

/** 菜单状态 */
export enum MenuStatus {
  /** MenuStatus_InActive - 禁用 */
  MenuStatus_InActive = "MenuStatus_InActive",
  /** MenuStatus_Active - 启用 */
  MenuStatus_Active = "MenuStatus_Active",
  UNRECOGNIZED = "UNRECOGNIZED",
}

/** 菜单类型 */
export enum MenuType {
  /** MenuType_Directory - 目录 */
  MenuType_Directory = "MenuType_Directory",
  /** MenuType_Menu - 菜单 */
  MenuType_Menu = "MenuType_Menu",
  /** MenuType_Button - 按钮 */
  MenuType_Button = "MenuType_Button",
  UNRECOGNIZED = "UNRECOGNIZED",
}

/** 获取当前角色的全部权限请求 */
export interface MePermissionsRequest {
}

/** 获取当前角色的全部权限响应 */
export interface MePermissionsResponse {
  /** 权限按钮 */
  permissions: string[];
  /** 权限菜单 */
  menus: MenuInfo[];
}

/** 权限菜单信息 */
export interface MenuInfo {
  /** 菜单id */
  id: string;
  /** 图标 */
  icon: string;
  /** 是否系统内置 */
  isSystem: boolean;
  /** 排序 */
  order: number;
  /** 父级菜单id */
  parentId: string;
  /** 路径 */
  path: string;
  /** 状态 */
  status: MenuStatus;
  /** 标题 */
  title: string;
  /** 类型 */
  type: MenuType;
  /** 创建时间 */
  createTime:
    | Date
    | undefined;
  /** 更新时间 */
  updateTime:
    | Date
    | undefined;
  /** 子权限菜单 */
  children: MenuInfo[];
}
