// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.31.1
// source: v1/system.proto

/* eslint-disable */

export const protobufPackage = "v1";

/** 菜单状态 */
export enum MenuStatus {
  /** MenuStatus_InActive - 禁用 */
  MenuStatus_InActive = "MenuStatus_InActive",
  /** MenuStatus_Active - 启用 */
  MenuStatus_Active = "MenuStatus_Active",
  UNRECOGNIZED = "UNRECOGNIZED",
}

/** 菜单类型 */
export enum MenuType {
  /** MenuType_Directory - 目录 */
  MenuType_Directory = "MenuType_Directory",
  /** MenuType_Menu - 菜单 */
  MenuType_Menu = "MenuType_Menu",
  /** MenuType_Button - 按钮 */
  MenuType_Button = "MenuType_Button",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum RoleStatus {
  /** RoleStatus_InActive - 停用 */
  RoleStatus_InActive = "RoleStatus_InActive",
  /** RoleStatus_Active - 启用 */
  RoleStatus_Active = "RoleStatus_Active",
  UNRECOGNIZED = "UNRECOGNIZED",
}

/** 获取当前角色的全部权限请求 */
export interface MePermissionsRequest {
}

/** 获取当前角色的全部权限响应 */
export interface MePermissionsResponse {
  /** 权限按钮 */
  permissions: string[];
  /** 权限菜单 */
  menus: MenuInfo[];
}

/** 权限菜单信息 */
export interface MenuInfo {
  /** 菜单id */
  id: string;
  /** 图标 */
  icon: string;
  /** 是否系统内置 */
  isSystem: boolean;
  /** 排序 */
  order: number;
  /** 父级菜单id */
  parentId: string;
  /** 路径 */
  path: string;
  /** 状态 */
  status: MenuStatus;
  /** 标题 */
  title: string;
  /** 类型 */
  type: MenuType;
  /** 权限标识 */
  permissions: string;
  /** 创建时间 */
  createTime:
    | Date
    | undefined;
  /** 更新时间 */
  updateTime:
    | Date
    | undefined;
  /** 子权限菜单 */
  children: MenuInfo[];
}

/** 管理员获取全部权限菜单请求 */
export interface AdminPermissionsRequest {
}

/** 管理员获取全部权限菜单响应 */
export interface AdminPermissionsResponse {
  /** 权限菜单 */
  menus: MenuInfo[];
}

/** 管理员获取单个权限菜单请求 */
export interface AdminPermissionsInfoRequest {
  menuId: string;
}

/** 管理员获取单个权限菜单响应 */
export interface AdminPermissionsInfoResponse {
  /** 权限菜单信息 */
  menu: MenuInfo | undefined;
}

/** 管理员添加权限菜单请求 */
export interface AdminAddPermissionsRequest {
  /** 类型 */
  type: MenuType;
  /** 父级菜单id */
  parentId: string;
  /** 标题 */
  title: string;
  /** 图标 */
  icon: string;
  /** 排序 */
  order: number;
  /** 路径 */
  path: string;
  /** 状态 */
  status: MenuStatus;
  /** 权限标识 */
  permissions: string;
}

/** 管理员添加权限菜单响应 */
export interface AdminAddPermissionsResponse {
}

/** 管理员编辑权限菜单请求 */
export interface AdminEditPermissionsRequest {
  /** 菜单id */
  menuId: string;
  /** 标题 */
  title: string;
  /** 图标 */
  icon: string;
  /** 排序 */
  order: number;
  /** 路径 */
  path: string;
  /** 状态 */
  status: MenuStatus;
  /** 权限标识 */
  permissions: string;
}

/** 管理员编辑权限菜单响应 */
export interface AdminEditPermissionsResponse {
}

/** 管理员删除权限菜单请求 */
export interface AdminDeletePermissionsRequest {
  menuId: string;
}

/** 管理员删除权限菜单响应 */
export interface AdminDeletePermissionsResponse {
}

/** 管理员获取角色列表请求 */
export interface AdminRolesRequest {
  /** 页 */
  page: number;
  /** 页数量 */
  pageSize: number;
  /** 状态条件筛选 */
  status?:
    | RoleStatus
    | undefined;
  /** 角色名称筛选 */
  name?: string | undefined;
}

/** 管理员获取角色列表响应 */
export interface AdminRolesResponse {
  /** 角色列表 */
  roles: RoleInfo[];
  /** 实际页 */
  page: number;
  /** 实际页 */
  pageSize: number;
  /** 总数 */
  total: number;
}

/** 角色详情 */
export interface RoleInfo {
  /** 角色id */
  roleId: string;
  /** 角色描述 */
  description: string;
  /** 是否内置角色 */
  isBuiltin: boolean;
  /** 角色昵称 */
  name: string;
  /** 角色状态 */
  status: RoleStatus;
  /** 创建时间 */
  createTime:
    | Date
    | undefined;
  /** 更新时间 */
  updateTime:
    | Date
    | undefined;
  /** 角色菜单id */
  menuIds: string[];
}

/** 获取角色详情请求 */
export interface AdminRoleRequest {
  /** 角色id */
  roleId: string;
}

/** 获取角色详情响应 */
export interface AdminRoleResponse {
  /** 角色信息 */
  role: RoleInfo | undefined;
}

/** 添加角色请求 */
export interface AdminAddRoleRequest {
  /** 角色描述 */
  description: string;
  /** 角色昵称 */
  name: string;
  /** 角色状态 */
  status: RoleStatus;
  /** 角色菜单id */
  menuIds: string[];
}

/** 添加角色响应 */
export interface AdminAddRoleResponse {
  /** 角色信息 */
  role: RoleInfo | undefined;
}

/** 修改角色请求 */
export interface AdminEditRoleRequest {
  /** 角色id */
  roleId: string;
  /** 角色描述 */
  description: string;
  /** 角色昵称 */
  name: string;
  /** 角色状态 */
  status: RoleStatus;
  /** 角色菜单id */
  menuIds: string[];
}

/** 修改角色响应 */
export interface AdminEditRoleResponse {
  /** 角色信息 */
  role: RoleInfo | undefined;
}

/** 删除角色请求 */
export interface AdminDeleteRoleRequest {
  /** 角色id */
  roleId: string;
}

/** 删除角色响应 */
export interface AdminDeleteRoleResponse {
}
