package biz

import (
	"fmt"

	"momoko/pkg/response"
)

var (
	ErrSystem = func(err error) error {
		return response.BadRequest(500, fmt.Sprintf("系统错误:%v", err))
	}
	ErrAdminNotFound              = response.BadRequest(500, "用户不存在")
	ErrInvalidPassword            = response.BadRequest(500, "密码错误")
	ErrTokenInvalid               = response.BadRequest(401, "token invalid")
	ErrUserNoRole                 = response.BadRequest(500, "用户没有角色")
	ErrNoPermission               = response.BadRequest(500, "权限不足")
	ErrUserInactive               = response.BadRequest(500, "账号已停用")
	ErrRegisterDisabled           = response.BadRequest(500, "注册已关闭")
	ErrUsernameLoginDisabled      = response.BadRequest(500, "用户名登录已关闭")
	ErrEmailLoginDisabled         = response.BadRequest(500, "邮箱登录已关闭")
	ErrEmailNot                   = response.BadRequest(500, "邮箱未启用")
	ErrEmailNotFound              = response.BadRequest(500, "邮件模板未配置")
	ErrEmailInvalid               = response.BadRequest(500, "邮箱格式不正确")
	ErrEmailRegistered            = response.BadRequest(500, "邮箱已注册")
	ErrUsernameEmpty              = response.BadRequest(500, "用户名不能为空")
	ErrPasswordEmpty              = response.BadRequest(500, "密码不能为空")
	ErrEmailEmpty                 = response.BadRequest(500, "邮箱不能为空")
	ErrUsernameRegistered         = response.BadRequest(500, "用户名已注册")
	ErrUsernameEmailRegistered    = response.BadRequest(500, "用户名或邮箱已注册")
	ErrEmailCodeInvalid           = response.BadRequest(500, "邮箱验证码错误或已过期")
	ErrEmailTemplateType          = response.BadRequest(500, "邮件模板类型不正确")
	ErrEmailTemplateSubject       = response.BadRequest(500, "邮件主题不能为空")
	ErrEmailTemplateContent       = response.BadRequest(500, "邮件模板内容不能为空")
	ErrInstanceNotFound           = response.BadRequest(500, "实例不存在")
	ErrInstanceAccess             = response.BadRequest(500, "您没有该实例权限")
	ErrInstanceTypeName           = response.BadRequest(500, "类型名称不能为空")
	ErrInstanceTypeID             = response.BadRequest(500, "类型ID不能为空")
	ErrSSHHostInvalid             = response.BadRequest(500, "SSH服务端参数无效")
	ErrSSHAuthInvalid             = response.BadRequest(500, "SSH认证方式无效")
	ErrSSHCredentialInvalid       = response.BadRequest(500, "SSH凭据不能为空")
	ErrSSHHostAccess              = response.BadRequest(500, "您没有该SSH服务端权限")
	ErrAPIKeyNameEmpty            = response.BadRequest(500, "API Key名称不能为空")
	ErrAPIKeyNotFound             = response.BadRequest(500, "API Key不存在")
	ErrAPIKeyGenerate             = response.BadRequest(500, "API Key生成失败")
	ErrNetworkNotImplemented      = response.BadRequest(500, "网络管理功能未实现")
	ErrFileNotExist               = response.BadRequest(500, "文件不存在")
	ErrFileTaskNotFound           = response.BadRequest(500, "文件任务不存在")
	ErrSign                       = response.BadRequest(500, "签名失败")
	ErrUploadRequestInvalid       = response.BadRequest(500, "上传请求参数无效")
	ErrShareNotFound              = response.BadRequest(500, "分享不存在或已失效")
	ErrShareForbidden             = response.BadRequest(500, "提取码错误或分享不可用")
	ErrUploadSessionNotFound      = response.BadRequest(500, "上传会话不存在")
	ErrUploadSessionConflict      = response.BadRequest(500, "上传会话与当前文件不匹配")
	ErrUploadPartInvalid          = response.BadRequest(500, "上传分片参数无效")
	ErrUploadIncomplete           = response.BadRequest(500, "文件分片尚未全部上传完成")
	ErrUploadCompleted            = response.BadRequest(500, "上传已完成")
	ErrInitializeDone             = response.BadRequest(500, "系统已初始化")
	ErrInitializeDatabaseEmpty    = response.BadRequest(500, "数据库配置不能为空")
	ErrInitializeAdminEmpty       = response.BadRequest(500, "超级管理员不能为空")
	ErrSub2APIConfigRequired      = response.BadRequest(500, "Sub2API 地址与管理员 API Key 不能为空")
	ErrSub2APIHomeConfig          = response.BadRequest(500, "开启公开首页前需完成 Sub2API 地址与管理员 API Key 配置")
	ErrSub2APISyncRunning         = response.BadRequest(500, "同步任务进行中，请稍后再试")
	ErrSub2APIRecordID            = response.BadRequest(500, "记录ID不能为空")
	ErrImageGenTokenInvalid       = response.BadRequest(500, "sub2api 登录已过期，请从控制台重新进入")
	ErrImageGenDisabled           = response.BadRequest(500, "生图功能未启用")
	ErrImageGenSrcHostForbidden   = response.BadRequest(500, "该 sub2api 站点未获授权调用生图")
	ErrImageGenApiKeyInvalid      = response.BadRequest(500, "apikey 无效或不存在")
	ErrImageGenGenerationNotFound = response.BadRequest(500, "生图任务不存在")
	ErrImageGenImageNotFound      = response.BadRequest(500, "图片不存在")
	ErrFileSourceNotFound         = response.BadRequest(500, "文件来源不存在")
	ErrFileSourceDisabled         = response.BadRequest(500, "文件来源已停用")
	ErrFileSourceUnsupported      = response.BadRequest(500, "当前文件来源不支持该操作")
	ErrFileSourceType             = response.BadRequest(500, "文件来源类型不合法")
	ErrShareSignInvalid           = response.BadRequest(500, "分享会话已失效，请重新验证")
	ErrTaskNotFound               = response.BadRequest(500, "任务不存在")
)
